### ISSUE TITLE
ImGui flickering issue with the test harness app

### ISSUE THREAD

**Issue by alextardif-zmi** [NVIDIAGameWorks/RTXGI-DDGI#1]
On a 2080 with latest drivers, running in release. The interface flickers in and out pretty frequently, and is most visible with vsync disabled. It's probably a sync/barrier issue, but I didn't have a chance to debug that myself.

**Comment by jspjutNV** [comment]
I tried to reproduce this flicker on a Titan Xp with driver version 445.75 and I couldn't get it to show up on either a 240 Hz display, or a 60 Hz display. Which driver version were you using?

**Comment by alextardif-zmi** [comment]
I was on 442.74 (3/13/2020), and on a 60Hz display as well.

**Comment by acmarrs-nvidia** [comment]
I tried 445.75 (latest driver) with an RTX 2080, on a G-Sync 120Hz display and a regular 60Hz display. Flickering does not happen. Could you give the latest driver a try?

**Comment by alextardif-zmi** [comment]
Gah. As expected, no flicker on this newer driver, sorry for the waste of time!
