### ISSUE TITLE
"if (dot(farthestDirection, DDGIGetProbeRayDirection(farthestFrontfaceIndex, DDGIVolume.numRaysPerProbe, DDGIVolume.probeRayRotationTransform)) <= 0.f)" Error in calculation code when probe position is automatically adjusted

### ISSUE THREAD

**Issue by haozhan** [NVIDIAGameWorks/RTXGI-DDGI#12]
ProbeRelocationCS.hlsl line 90 code

![DevCap_20200430_091627](https://user-images.githubusercontent.com/7542479/80662320-8dc56080-8ac3-11ea-977f-1477d04dd74a.png)

Here the two vectors of the dot, which are written as the same.
Ithink the code here is to calculate the angle between the nearest trace ray and the farthest trace ray, and if it is greater than 180 degrees, it moves in the direction of the distant ray.

**Comment by jukim-nv** [comment]
This should be fixed in the next release.
