### ISSUE TITLE
DDGIVolume::UpdateProbes() - border update dispatches too many threads

### ISSUE THREAD

**Issue by haozhan** [NVIDIAGameWorks/RTXGI-DDGI#13]
DDGIVolume.cpp line 500 and line 527 code “numThreadsX = (probeCountX * 2);”， the number of thread groups in which why multiply by 2, feel completely wasteful.

**Comment by acmarrs-nvidia** [comment]
I think you are referring to lines [496 ](https://github.com/NVIDIAGameWorks/RTXGI/blob/master/rtxgi-sdk/src/ddgi/DDGIVolume.cpp#L523)and [523](https://github.com/NVIDIAGameWorks/RTXGI/blob/aef6d367ac64785d87ac4450d20b00354c1cb1e0/rtxgi-sdk/src/ddgi/DDGIVolume.cpp#L496) (see permalinks). 

Good catch. Each border update shader kernel handles **both** the left and right columns (as well the top and bottom rows) of a probe's 1 texel border, so there is no need to multiply the number of threads in the X dimension by two.

**Comment by haozhan** [comment]
Yes, the line numbers are 496 and 523 lines, maybe my code is not updated or the editor is not the same display is error. now the problem has been identified and solved. thank you very much and have a good cooperation.
