### ISSUE TITLE
Question: Use RTXGI on packed UE 4.25.3 from Epic Game Launcher

### ISSUE THREAD

**Issue by christianstamati** [NVIDIAGameWorks/RTXGI-DDGI#16]
Hi all,
I tried the plugin on UE 4.25.3 Source and UE 4.25.3 NvRTX and it works like magic! Thank you very much!
I'm currently working on a project using the UE version from Epic Games Launcher and I would like to use the plugin. I did the same steps and after I activate the plugin the Engine asks me to compile the plugin but Idk how to do this because the engine doesn't come with Vs files it's packed. In the previous test's when I had this message I just recompiled the engine and it worked. I tried other methods but didn't work:
- I moved the plugin in a C++ project and then I compiled it
- I tried to use the compiled version from UE 4.25.3 Source, I just moved the plugin in the UE standard version

Here's all the steps => https://youtu.be/iSm9XDJXSV8

**Comment by grgc25** [comment]
Hi! I´m Stuck in the same place as you, with either the dlss branch or the epic store branch i´m getting the exact same issue. I was just about to post it too.

**Comment by MartianDays** [comment]
@christianstamati one does not simply get rtxgi on the base ue4 distro from the epic launcher. Kidding aside, it does require a source build. There's a tidbit in the documentation that suggests otherwise that I keep intending to mention [slipped my mind] which I think might be what's confusing you? Anyway, it *does* require an alteration to source so you can't just use it from a launcher distro or a project directory.

@grgc25 I know what this is, I think! After you've got Unreal Engine's "stuff" downloaded and you're about ready to double-click "GenerateProjectFiles.bat", STOP. Before you generate project files, THEN copy the RTXGI plugin per the documentation included. AFTER you've done that, THEN run GenerateProjectFiles.bat, then open the sln as normal and build the solution.

**Comment by grgc25** [comment]
I will try that, thank you @MartianDays 

So
- unpack
- check dependency
- apply patch
- generate proyect files
- compile


(insert interstellar maneuver reference here)

**Comment by grgc25** [comment]
Also, dumb question, does this plugin have the caustics stuff? i don't see a reference to it anywhere so I'm asking just in case 😅

**Comment by MartianDays** [comment]
> 
> 
> I will try that, thank you @MartianDays
> 
> So
> 
>     * unpack
> 
>     * check dependency
> 
>     * apply patch
> 
>     * generate project files
> 
>     * compile
> 
> 
> (insert interstellar maneuver reference here)

I think that should work, yep. As I recall, that's how I got up and running. Let us know if it works! :D

**Comment by MartianDays** [comment]
> 
> 
> Also, dumb question, does this plugin have the caustics stuff? i don't see a reference to it anywhere so I'm asking just in case 😅

As far as I know, no, this plugin is RTXGI only. :)

**Comment by christianstamati** [comment]
Ok, everything clear thanksssss ;)!

**Comment by jinngonqui** [comment]
I'm confuzzled by other official statements about what Engine "editions" the 'plugin' can be used with / installed on ... 
. 
Richard Cowgill (RTX Unreal Engine Evangelist, Nvidia) speaking with Victor Brodin (Community Manager, Epic) in demonstration/discussion video of "Inside Unreal" of RTXGI and DLSS 2.0 (indicated as still not as readily available as RTXGI) ... 
... from <https://www.youtube.com/watch?v=ZefvmV1pdP8&t=3908s> the transcript <https://epicgames.ent.box.com/s/q4vzj8n0vz6n88la8ig2v8xo9obbtboo> shows (and the audio seems to coordinate): 
"You know, RTXGI is here.01:05:08.480 --> 01:05:09.560Anybody can get it.01:05:09.560 --> 01:05:11.590Just sign up for ourdevelopment program,01:05:11.590 --> 01:05:13.600and yougot accessto the source.01:05:13.600 --> 01:05:17.780And **you can plug thatright into Unreal 4 and go.01:05:17.780 --> 01:05:19.265You don't have tobe on our branch.01:05:19.265 --> 01:05:20.890You know, we've gota version that will01:05:20.890 --> 01:05:24.010work with the mainline Unreal."** 
. 
Its greatest value is as a plugin to the Launcher edition. 
. 
Will such be a thing? 
Is a Launcher-born Engine "edition" plugin in development? 
. 
Doesn't the word "plugin" preclude the concept of "source" manipulation?

**Comment by grgc25** [comment]
> > I will try that, thank you @MartianDays
> > So
> > ```
> > * unpack
> > 
> > * check dependency
> > 
> > * apply patch
> > 
> > * generate project files
> > 
> > * compile
> > ```
> > 
> > 
> > (insert interstellar maneuver reference here)
> 
> I think that should work, yep. As I recall, that's how I got up and running. Let us know if it works! :D



Yep it does work if you set it in this order.

**Comment by Atrix256** [comment]
@jinngonqui 

> Doesn't the word "plugin" preclude the concept of "source" manipulation?

Yes technically, but no in practice.  Some things the plugin needs to be able to do is not currently possible with the plugin system. We are working with epic to see about getting the engine changes in to make this easier in the future though.

**Comment by grgc25** [comment]
Come to think of it, it does make sense to install the plugin before compiling if there´s that much changes.

Not sure if this is the right place to ask but... Any idea on how to try the caustics stuff? in the livestream they said its possible to merge both the plugin and the caustics stuff but i havce found no reference about it.
