### ISSUE TITLE
Documentation Confuzzlement

### ISSUE THREAD

**Issue by MartianDays** [NVIDIAGameWorks/RTXGI-DDGI#18]
@Atrix256 @acmarrs-nvidia I spotted a tidbit in step 1 of the documentation for setting up the Unreal Engine Plugin that caused me some confusion when I first tried to get rtxgi up and running, and I think ticket #16 [here](https://github.com/NVIDIAGameWorks/RTXGI/issues/16#issue-696083595) could be a reflection of this confusion, so I wonder if it should be omitted or edited for clarity? I'll attach a screenshot.

![Capture](https://user-images.githubusercontent.com/15644824/92535519-3f03a200-f1ec-11ea-9131-6e73db07e7cb.PNG)

**Comment by jinngonqui** [comment]
comment on #16, also relevant more directly here: https://github.com/NVIDIAGameWorks/RTXGI/issues/16#issuecomment-689275627

**Comment by Atrix256** [comment]
Ah, thanks. Yeah, it does not work with the launcher, you need to build from source because the patch contains engine changes.

**Comment by Atrix256** [comment]
Updated, thanks!
