### ISSUE TITLE
SSGI not working with RTXGI

### ISSUE THREAD

**Issue by aliuhad** [NVIDIAGameWorks/RTXGI-DDGI#19]
When SSGI is enabled RTXGI gets off.
r.SSGI.Enable 1

Invisible emissive objects not contributing to RTXGI, but works when visible.

**Comment by Atrix256** [comment]
Right now you have to choose which one you want - SSGI or RTXGI - but the next patch will allow them to both work at the same time.

**Comment by Atrix256** [comment]
Just to ping this @aliuhad - the latest patch makes it so both can be used together.
Thanks!
