### ISSUE TITLE
data\gltf\sponza\ directory resources do not exist.

### ISSUE THREAD

**Issue by haozhan** [NVIDIAGameWorks/RTXGI-DDGI#20]
data\gltf\sponza\ directory resources do not exist, is it missing?

**Comment by acmarrs-nvidia** [comment]
[As detailed in the documentation](https://github.com/NVIDIAGameWorks/RTXGI/blob/184e35a204b656c15697d863833edec190a1d3e2/docs/manual/Harness.html#L650), the Sponza scene is not included in the SDK distribution. We do not own those assets. You can download the Sponza scene from Khronos: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza
