### ISSUE TITLE
(UE4) Probes not accumulating correct color 

### ISSUE THREAD

**Issue by triverske** [NVIDIAGameWorks/RTXGI-DDGI#21]
![lightprobe](https://user-images.githubusercontent.com/933373/93556718-0461de00-f93f-11ea-9ce8-d6a6d72e6e5a.png)

I get a lot of lighting errors similar to this when using multiple volumes that overlap.
Unreal 4.25.3
RTXGI Plugin V0.0
RTXGI SDK Version 1.1

**Comment by Atrix256** [comment]
We haven't seen problems with overlapping volumes so that's surprising..  A couple questions...
1. How many volumes are in this level?
2. Is the lower left the ddgiprobevis which shows what the probes see? if so, that looks really dark, like maybe your light source(s) aren't configured to show up in raytracing... what kind of light sources are you using on this map?
3. Are you using any volumes marked as "RuntimeStatic" being true?
Thanks!

**Comment by triverske** [comment]
Hey there. 

1. I've tested with 2 and 3 volumes and got similar results
2. Yes, that's ddgiprobevis. There's a large red emissive light above everything, so I'm expecting it to stay consistent on the flat grid area.
3. I don't think so, but I am unable to verify. I don't seem to have anything regarding the static/movable state in the details panel on volumes.

![edge](https://user-images.githubusercontent.com/933373/93659686-aa7c1980-fa0d-11ea-8f01-6866e8b6c398.png)

Here's a close up image of what's going on. One possible lead is that probes may be retaining their colors after moving? I get varying, but not perfect results by messing with the probe moving/scrolling options.

<img width="1170" alt="odd colors" src="https://user-images.githubusercontent.com/933373/93659715-f038e200-fa0d-11ea-9923-e8378e4f8bb4.PNG">

There's also some stuff like this where bright colors will persist indefinitely in the probes without an actual light source to pull from.

Lots of fun to be had with realtime global illumination!

**Comment by Atrix256** [comment]
Apologies for the delay on this one... could you by chance share a map as a minimal example of the problem?  We haven't seen anything like this internally or from our other users so it's a bit of a mystery.
Thanks!

**Comment by triverske** [comment]
Not a problem, I will quickly get something together

**Comment by triverske** [comment]
![HighresScreenshot00000](https://user-images.githubusercontent.com/933373/97915764-a08d4c00-1d17-11eb-91bb-b80f00873fac.png)
So a hypothesis: It looks like whenever probes are no longer relevant they hold onto their color which may be causing some weird issues? Seems to especially happen in cases where emissive light is changing frequently, the project in the link below is a very barebones example of this behavior.

https://app.box.com/s/bmzpt5mjob2c2yzkq30h3zfd2ormjxvs

**Comment by Atrix256** [comment]
Thank you for the test map and project!
They do indeed, but believe it or not, that is a feature, not a bug.
The reason for this has to do with dynamic objects.  If you have a probe where the player is, and the player walks through it, it would go black when it was inside of them and went to sleep.  If the player stepped off of the probe, it would start contributing light "at black" so would make things around it be too dark, until it figured out the lighting again and started giving the correct bounce light.
The way this is addressed is that probes retain their lighting information when they go to sleep, in case they wake up and need to start contributing lighting again.
Even though they retain their lighting information, the sleeping probes won't contribute lighting to the scene.
We do have some more work done that we are hoping to get out soon. It would be interesting to see if you still see that oddity you first mentioned with the new code.  Or, if you are able to find some kind of minimal reproduction of that problem i can totally take a look.
This one at least is working as designed and should be g2g.

**Comment by triverske** [comment]
So after messing around with it more and more I can't exactly pin down the issue, but I think it's with geometry needing to be "refreshed" because after moving some of the meshes I was having odd color issues with in the editor they started working as expected. I'm ready to close this off, as I don't have a reasonable way to really present the issue anymore.

**Comment by Atrix256** [comment]
Hrm ok. You have screenshots so something is definitely off, but it's unclear what it is... one of those "Heisenbugs" where it disappears when you try to debug it.
We'll keep looking on our side as well. With luck, if there is an issue, it's been fixed in the latest code. (still working on getting that out)

**Comment by triverske** [comment]
Looking forward to playing with the new releases, I'll close this for now and if the issue resurfaces in a way I can reproduce I'll post an update here. Thanks for the help!
