### ISSUE TITLE
NvLink Multi-GPU support

### ISSUE THREAD

**Issue by SephirothFFKH** [NVIDIAGameWorks/RTXGI-DDGI#24]
I have tried the various UE4 RTX branches but none seems to be making use of NvLink Multi-GPU support as only one of my two RTX 2080Ti are in use. I did read about a raytracing multi-GPU solution in the Nvidia Dev Blog: Rendering Perfect Reflections and Refractions in Path-Traced Games (https://developer.nvidia.com/blog/rendering-perfect-reflections-and-refractions-in-path-traced-games/) I was wandering if a similar solution could be implemented in this or any of the Nvidia custom RTX UE4 branches to get at least some multi-GPU scaling?

Thank you

**Comment by Atrix256** [comment]
Hey Sephiroth. Yeah, UE does support NvLink multi GPU, so our branches of UE does as well.
Make sure you are running in dx12 and that you are using "-MaxGPUCount=#" to set the number of GPUs max, or -AFR to set it to the max.
Some things take better advantage of it than others though, so things like path tracing and light mass may benefit more than others.
