### ISSUE TITLE
RTXGI Indirect Lighting Not Visible in RT Reflections

### ISSUE THREAD

**Issue by MartianDays** [NVIDIAGameWorks/RTXGI-DDGI#27]
G'Mornin' all~~ :D

Wondering if this is by design, a limitation, or perhaps a bug maybe? I'm noticing that, with a prototype I'm putting together to test Unreal Engine 4, RTXGI, and optimizations (I'm experimenting in [This  NVRTX branch](https://github.com/NvRTX/UnrealEngine/tree/rtx-dlss-4.25.4) and RTXGI plugin from 4.25.3) to get familiar with everything, that RTXGI lighting isnt' visible in RT reflections. Would be aesthetically gorgeous if it could optionally contribute lighting to reflections! While screen space hybridization of rt reflections can kinda fake this I guess, it's still pretty obvious and jarring in this case I've tried - especially on large flat surfaces like a shiny floor, water, etc.

Anyway, here's a screenie of what I see. Thanks so much for this plugin and everything y'all are doing to push real-time rendering to the next level! :D

![HighresScreenshot00018](https://user-images.githubusercontent.com/15644824/100475540-38bced80-3098-11eb-9b59-0cff9cb084f1.png)

**Comment by Atrix256** [comment]
Good morning!

You are correct, it does not work in raytraced reflections currently.  We are thinking about ways to make that happen, but challenges to overcome include: letting plugins inject shader code into the core lighting shaders of the engine, and making it so those shaders can access any of N different textures which are of different sizes (any reflected pixel may need to read from any probe volume).  Bindless would help with the second but isn't available, so need to find another way.

Once RTXGI works in raytraced reflections, there are other effects in unreal that don't work in raytraced reflections - like RTAO if I remember right - so reaching parity will have more work beyond RTXGI unfortunately.  But yes, we are trying to find the best way to support it!
