### ISSUE TITLE
TestHarness.exe produces incorrect log messages when used without arguments

### ISSUE THREAD

**Issue by pixnblox** [NVIDIAGameWorks/RTXGI-DDGI#3]
Launching TestHarness.exe without arguments produces "Error: failed to initialize D3D12!" in the log when in fact it should exit immediately. It turns out that it is reading the executable as a config file (!) due to weirdness with `CommandLineToArgvW`. If there are no arguments, that function will return a single argument with the executable path.

Also, it seemed strange that the config file use paths relative to the working directory, rather than relative to the config file itself.

I am making a pull request that fixes both of these things, generally improving the startup and error reporting behavior.

**Comment by pixnblox** [comment]
This is resolved (and more) with PR #4. I can't seem to link this issue to it, however. (possibly a permissions issue)

**Comment by acmarrs-nvidia** [comment]
Addressed in [the latest update](https://github.com/NVIDIAGameWorks/RTXGI/commit/18a35b1ac87d9bf3f35dabf332feb0187737b0f0).
