### ISSUE TITLE
UE4: CTD crash with Async Loading Thread Enabled

### ISSUE THREAD

**Issue by scragnog** [NVIDIAGameWorks/RTXGI-DDGI#30]
Using NvRTX4.25.4 and latest version of RTXGI plugin.

As soon as 'Async Loading Thread Enabled' is checked in project settings, the packaged game will immediately crash when loading any level with a DDGI Volume in. Tested and confirmed in 2 projects, including the NGXSettingsUI test project.

Further error details below:

> Assertion failed: IsInGameThread() [File:P:/NvRTX/Engine/Source/Runtime/RenderCore/Private/RenderingThread.cpp] [Line: 1335]
> 
> OrvilleFanGame_Win64_DebugGame!AssertFailedImplV() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:100]
> OrvilleFanGame_Win64_DebugGame!FDebug::CheckVerifyFailedImpl() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:450]
> OrvilleFanGame_Win64_DebugGame!GetPendingCleanupObjects() [P:\NvRTX\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:1358]
> OrvilleFanGame_Win64_DebugGame!FlushRenderingCommands() [P:\NvRTX\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:1261]
> OrvilleFanGame_Win64_DebugGame!UDDGIVolumeComponent::Serialize() [P:\NvRTX\Engine\Plugins\Runtime\Nvidia\RTXGI\Source\RTXGI\Private\DDGIVolumeComponent.cpp:675]
> OrvilleFanGame_Win64_DebugGame!FAsyncPackage::EventDrivenSerializeExport() [P:\NvRTX\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp:3179]
> OrvilleFanGame_Win64_DebugGame!FAsyncPackage::ProcessImportsAndExports_Event() [P:\NvRTX\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp:3506]
> OrvilleFanGame_Win64_DebugGame!<lambda_09983e57678d61245a3f00566aacef3f>::operator()() [P:\NvRTX\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp:2286]
> OrvilleFanGame_Win64_DebugGame!FAsyncLoadingThread::ProcessAsyncLoading() [P:\NvRTX\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp:4037]
> OrvilleFanGame_Win64_DebugGame!FAsyncLoadingThread::TickAsyncThread() [P:\NvRTX\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp:4820]
> OrvilleFanGame_Win64_DebugGame!FAsyncLoadingThread::Run() [P:\NvRTX\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp:4747]
> OrvilleFanGame_Win64_DebugGame!FRunnableThreadWin::Run() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]

**Comment by acmarrs-nvidia** [comment]
Thanks for reporting this @scragnog. This will be fixed in the next plugin update (coming soon).
