### ISSUE TITLE
UE4: Unable to package if Vulkan is enabled as an RHI

### ISSUE THREAD

**Issue by scragnog** [NVIDIAGameWorks/RTXGI-DDGI#31]
If the Vulkan option is checked in the project settings, and the RTXGI plugin is added to the project, packaging fails entirely. Error message during packaging follows:

> UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Warning: 2 Shader compiler errors compiling global shaders for platform SF_VULKAN_SM5:
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Warning: P:/NvRTX/Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/Common.ush(68): Shader FVolumeVisualizeShaderPS, Permutation 0, VF None:
UATHelper: Packaging (Windows (64-bit)):       error: Illegal use of reserved word 'packed'
UATHelper: Packaging (Windows (64-bit)):   
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Warning: P:/NvRTX/Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/Common.ush(68): Shader FVolumeVisualizeShaderPS, Permutation 0, VF None:
UATHelper: Packaging (Windows (64-bit)):       error: syntax error, unexpected ERROR_TOK, expecting IDENTIFIER or TYPE_IDENTIFIER or NEW_IDENTIFIER
UATHelper: Packaging (Windows (64-bit)):   
PackagingResults: Warning: 2 Shader compiler errors compiling global shaders for platform SF_VULKAN_SM5:
PackagingResults: Warning: P:/NvRTX/Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/Common.ush(68): Shader FVolumeVisualizeShaderPS, Permutation 0, VF None:
PackagingResults: Error: Illegal use of reserved word 'packed'
PackagingResults: Warning: P:/NvRTX/Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/Common.ush(68): Shader FVolumeVisualizeShaderPS, Permutation 0, VF None:
PackagingResults: Error: syntax error, unexpected ERROR_TOK, expecting IDENTIFIER or TYPE_IDENTIFIER or NEW_IDENTIFIER
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Error: Errors compiling global shader FVolumeVisualizeShaderPS  :
UATHelper: Packaging (Windows (64-bit)):   
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Error:  /Plugin/RTXGI/Private/SDK/Common.ush(68): error: Illegal use of reserved word 'packed'
UATHelper: Packaging (Windows (64-bit)):   LogShaderCompilers: Error:  /Plugin/RTXGI/Private/SDK/Common.ush(68): error: syntax error, unexpected ERROR_TOK, expecting IDENTIFIER or TYPE_IDENTIFIER or NEW_IDENTIFIER
UATHelper: Packaging (Windows (64-bit)):   LogOutputDevice: Warning:
UATHelper: Packaging (Windows (64-bit)):   
UATHelper: Packaging (Windows (64-bit)):   Script Stack (0 frames):
UATHelper: Packaging (Windows (64-bit)):   
PackagingResults: Error: Errors compiling global shader FVolumeVisualizeShaderPS  :
PackagingResults: Error:     /Plugin/RTXGI/Private/SDK/Common.ush(68): error: Illegal use of reserved word 'packed'
PackagingResults: Error:     /Plugin/RTXGI/Private/SDK/Common.ush(68): error: syntax error, unexpected ERROR_TOK, expecting IDENTIFIER or TYPE_IDENTIFIER or NEW_IDENTIFIER
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: begin: stack for UAT
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: === Critical error: ===
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Fatal error: [File:P:/NvRTX/Engine/Source/Runtime/Engine/Private/ShaderCompiler/ShaderCompiler.cpp] [Line: 5003]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Failed to compile global shader FVolumeVisualizeShaderPS  .  Enable 'r.ShaderDevelopmentMode' in ConsoleVariables.ini for retries.
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007fff8f4e3e49 KERNELBASE.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffef0ebeaf6 UE4Editor-Core.dll!ReportAssert() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Windows\WindowsPlatformCrashContext.cpp:1541]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffef0ec1ed8 UE4Editor-Core.dll!FWindowsErrorOutputDevice::Serialize() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Windows\WindowsErrorOutputDevice.cpp:78]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffef0c4e3bd UE4Editor-Core.dll!FOutputDevice::LogfImpl() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Misc\OutputDevice.cpp:61]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffeeeb76436 UE4Editor-Engine.dll!ProcessCompiledGlobalShaders() [P:\NvRTX\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp:5023]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffeeeb78067 UE4Editor-Engine.dll!FShaderCompilingManager::ProcessCompiledShaderMaps() [P:\NvRTX\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp:2453]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffeeeb75569 UE4Editor-Engine.dll!FShaderCompilingManager::ProcessAsyncResults() [P:\NvRTX\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp:2981]
PackagingResults: Error: begin: stack for UAT
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffeeeb7def2 UE4Editor-Engine.dll!RecompileShadersForRemote() [P:\NvRTX\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp:4891]
PackagingResults: Error: === Critical error: ===
PackagingResults: Error: Fatal error: [File:P:/NvRTX/Engine/Source/Runtime/Engine/Private/ShaderCompiler/ShaderCompiler.cpp] [Line: 5003]
PackagingResults: Error: Failed to compile global shader FVolumeVisualizeShaderPS  .  Enable 'r.ShaderDevelopmentMode' in ConsoleVariables.ini for retries.
PackagingResults: Error: [Callstack] 0x00007fff8f4e3e49 KERNELBASE.dll!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007ffef0ebeaf6 UE4Editor-Core.dll!ReportAssert() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Windows\WindowsPlatformCrashContext.cpp:1541]
PackagingResults: Error: [Callstack] 0x00007ffef0ec1ed8 UE4Editor-Core.dll!FWindowsErrorOutputDevice::Serialize() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Windows\WindowsErrorOutputDevice.cpp:78]
PackagingResults: Error: [Callstack] 0x00007ffef0c4e3bd UE4Editor-Core.dll!FOutputDevice::LogfImpl() [P:\NvRTX\Engine\Source\Runtime\Core\Private\Misc\OutputDevice.cpp:61]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffeeb98c05d UE4Editor-UnrealEd.dll!UCookOnTheFlyServer::SaveGlobalShaderMapFiles() [P:\NvRTX\Engine\Source\Editor\UnrealEd\Private\CookOnTheFlyServer.cpp:6504]
PackagingResults: Error: [Callstack] 0x00007ffeeeb76436 UE4Editor-Engine.dll!ProcessCompiledGlobalShaders() [P:\NvRTX\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp:5023]
PackagingResults: Error: [Callstack] 0x00007ffeeeb78067 UE4Editor-Engine.dll!FShaderCompilingManager::ProcessCompiledShaderMaps() [P:\NvRTX\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp:2453]
PackagingResults: Error: [Callstack] 0x00007ffeeeb75569 UE4Editor-Engine.dll!FShaderCompilingManager::ProcessAsyncResults() [P:\NvRTX\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp:2981]
PackagingResults: Error: [Callstack] 0x00007ffeeeb7def2 UE4Editor-Engine.dll!RecompileShadersForRemote() [P:\NvRTX\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp:4891]
PackagingResults: Error: [Callstack] 0x00007ffeeb98c05d UE4Editor-UnrealEd.dll!UCookOnTheFlyServer::SaveGlobalShaderMapFiles() [P:\NvRTX\Engine\Source\Editor\UnrealEd\Private\CookOnTheFlyServer.cpp:6504]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffeeb99267c UE4Editor-UnrealEd.dll!UCookOnTheFlyServer::StartCookByTheBook() [P:\NvRTX\Engine\Source\Editor\UnrealEd\Private\CookOnTheFlyServer.cpp:7745]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffeeb801582 UE4Editor-UnrealEd.dll!UCookCommandlet::CookByTheBook() [P:\NvRTX\Engine\Source\Editor\UnrealEd\Private\Commandlets\CookCommandlet.cpp:889]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffeeb82c57b UE4Editor-UnrealEd.dll!UCookCommandlet::Main() [P:\NvRTX\Engine\Source\Editor\UnrealEd\Private\Commandlets\CookCommandlet.cpp:595]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff62a83363a UE4Editor-Cmd.exe!FEngineLoop::PreInitPostStartupScreen() [P:\NvRTX\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:3391]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff62a82b7ec UE4Editor-Cmd.exe!GuardedMain() [P:\NvRTX\Engine\Source\Runtime\Launch\Private\Launch.cpp:127]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff62a82bb5a UE4Editor-Cmd.exe!GuardedMainWrapper() [P:\NvRTX\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff62a83e31d UE4Editor-Cmd.exe!WinMain() [P:\NvRTX\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff62a84040a UE4Editor-Cmd.exe!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007fff90937034 KERNEL32.DLL!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007fff91b9cec1 ntdll.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: end: stack for UAT
PackagingResults: Error: [Callstack] 0x00007ffeeb99267c UE4Editor-UnrealEd.dll!UCookOnTheFlyServer::StartCookByTheBook() [P:\NvRTX\Engine\Source\Editor\UnrealEd\Private\CookOnTheFlyServer.cpp:7745]
PackagingResults: Error: [Callstack] 0x00007ffeeb801582 UE4Editor-UnrealEd.dll!UCookCommandlet::CookByTheBook() [P:\NvRTX\Engine\Source\Editor\UnrealEd\Private\Commandlets\CookCommandlet.cpp:889]
PackagingResults: Error: [Callstack] 0x00007ffeeb82c57b UE4Editor-UnrealEd.dll!UCookCommandlet::Main() [P:\NvRTX\Engine\Source\Editor\UnrealEd\Private\Commandlets\CookCommandlet.cpp:595]
PackagingResults: Error: [Callstack] 0x00007ff62a83363a UE4Editor-Cmd.exe!FEngineLoop::PreInitPostStartupScreen() [P:\NvRTX\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:3391]
PackagingResults: Error: [Callstack] 0x00007ff62a82b7ec UE4Editor-Cmd.exe!GuardedMain() [P:\NvRTX\Engine\Source\Runtime\Launch\Private\Launch.cpp:127]
PackagingResults: Error: [Callstack] 0x00007ff62a82bb5a UE4Editor-Cmd.exe!GuardedMainWrapper() [P:\NvRTX\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
PackagingResults: Error: [Callstack] 0x00007ff62a83e31d UE4Editor-Cmd.exe!WinMain() [P:\NvRTX\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
PackagingResults: Error: [Callstack] 0x00007ff62a84040a UE4Editor-Cmd.exe!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
PackagingResults: Error: [Callstack] 0x00007fff90937034 KERNEL32.DLL!UnknownFunction []
PackagingResults: Error: [Callstack] 0x00007fff91b9cec1 ntdll.dll!UnknownFunction []
PackagingResults: Error: end: stack for UAT
UATHelper: Packaging (Windows (64-bit)): Took 170.17932s to run UE4Editor-Cmd.exe, ExitCode=3
UATHelper: Packaging (Windows (64-bit)): ERROR: Cook failed.
UATHelper: Packaging (Windows (64-bit)):        (see P:\NvRTX\Engine\Programs\AutomationTool\Saved\Logs\Log.txt for full exception trace)
PackagingResults: Error: Cook failed.
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Cook Failure

**Comment by acmarrs-nvidia** [comment]
Thanks for the message @scragnog. The RTXGI UE4 plugin does not yet support Vulkan, so shader compilation errors will occur if you try to package with the Vulkan RHI selected and the plugin installed. You will need to remove the plugin if you wish to use Vulkan.

**Comment by scragnog** [comment]
> Thanks for the message @scragnog. The RTXGI UE4 plugin does not yet support Vulkan, so shader compilation errors will occur if you try to package with the Vulkan RHI selected and the plugin installed. You will need to remove the plugin if you wish to use Vulkan.

Thanks for the reply.
Much like the other issue I raised regarding level corruption using Mac, is there no way to force the plugin into a disabled state on unsupported RHIs/platforms?
The main issue we have is that on our project we have Vulkan/DX11/DX12 support on windows with cross-compatibility with Metal on Mac.
It does seem as though the only way to retain support for these would be to remove the RTXGI plugin entirely, even though it's only intended use-case (currently) is DX12 on Windows.

Thanks.

**Comment by acmarrs-nvidia** [comment]
> is there no way to force the plugin into a disabled state on unsupported RHIs/platforms?

Thanks for letting us know about your use case. This is a good question that I don't know the answer to yet. I'll investigate and get back to you.

**Comment by jamiej** [comment]
@scragnog We've deployed RTXGI on two significantly different platforms. Consider reviewing the changes outlined https://github.com/NVIDIAGameWorks/RTXGI/issues/42

Regards,
Jamie

**Comment by acmarrs-nvidia** [comment]
This issue is fixed and will be in the next release.
