### ISSUE TITLE
UE4: RTXGI Plugin makes project incompatible with Mac

### ISSUE THREAD

**Issue by scragnog** [NVIDIAGameWorks/RTXGI-DDGI#32]
Implementing a DDGI volume in a level via the PC version of the editor with the RTXGI plugin enabled appears to make that level completely incompatible with the same version of the editor running on Mac. The level becomes completely inaccessible, being removed from the content browser entirely, even though the .umap exists on the disk.
My guess would be that the lighting data from RTXGI is stored in the umap file, which is causing an incompatibility.

Of course, it's not expected that RTXGI will function on Mac, but some sort of graceful fallback to at least allow the levels themselves to remain available would solve this particular problem.
As it stands currently, we can't have cross-compatibility with our project when implementing RTXGI.

Other notes:
- The Mac platform is not whitelisted in the RTXGI uplugin for obvious reasons. Enabling it results in compilation errors as expected, so it must be disabled at present.
- Removing DDGI volumes from the levels makes the level accessible via the Mac editor again.

Potential solutions:
- My understanding is that the GI created by RTXGI can be used on unsupported platforms in a static way, where this GI cannot be changed or updated at runtime. This would be an ideal solution.
- If the GI created by RTXGI cannot be used on Mac in any way, we at least need to be able to include the RTXGI plugin in a functioning state on Windows, and perhaps with an active but disabled state on Mac, so at least the DDGI volumes are recognised, and don't break compatibility with level assets.

**Comment by scragnog** [comment]
Hi,

I have a developer on my team here that would like to resolve this issue which is still unresolved by adding preprocessor conditions to the plugin to allow the project to work on Mac without RTXGI making all levels with DDGI volumes incompatible.

He's like to raise a pull request to this effect but does not currently have access to this repo, I'm the only member of my team that currently does.

Would it be possible to add github username 'Alanzote' to this repo, with pull request access?

Thanks.

**Comment by MartianDays** [comment]
Similar functionality was added to the UE4 DLSS plugin as well, earlier in the year when I requested it from that team as well, and is extremely invaluable so that a single project does not need to be split and maintained in several repos. I fully support this request.

**Comment by tiont** [comment]
Hi @scragnog. Thank you for reporting this and apologies for the delay. We have received the request to have RTXGI UE4 plugin run on Mac without errors and it is something that we are investigating. We hope to have an update on this issue in the near future.

With regards to access to the RTXGI source repo, we would need your developer to fill out the request form [here](https://developer.nvidia.com/rtxgi-sdk-get-started#sdk-latest-version), click thru the EULA, and provide their GitHub ID. Once that is complete, they will be granted read access to the repo.
