### ISSUE TITLE
RTXGI in open worlds

### ISSUE THREAD

**Issue by MiggyE** [NVIDIAGameWorks/RTXGI-DDGI#34]
Hi Nvidia, thanks for the great software. I was wondering what is the recommended way to use RTXGI in an open world setting. Is there a way to cascade RTXGI volumes or some other way to scale the probes up to large distances?

**Comment by acmarrs-nvidia** [comment]
Hi @MiggyE, for open / large world environments it is best to use a combination of static, dynamic, and infinite scrolling DDGIVolumes.

For example:
- Attach an infinite scrolling DDGIVolume to the player / camera and set the probe density to something fairly dense. This will produce dynamic GI in the near field around the player.
- Create DDGIVolumes in the open world in locations where you know GI will be prominent, but will be far enough away from the player to not be captured by the player-attached DDGIVolume. These volumes can be static (no RT at runtime) or dynamic depending on the circumstances (e.g. time of day or weather). The probe density of these volumes should be less than the infinite scrolling volume that is attached to the player.
- Create a large "global" DDGIVolume that has very low probe density, but covers the entire play space. This will produce GI for all areas not covered by the other volume types.
