### ISSUE TITLE
NvRTX 4.26.0 "patch does not apply" error

### ISSUE THREAD

**Issue by acmarrs-nvidia** [NVIDIAGameWorks/RTXGI-DDGI#35]
Hi, 

I've downloaded the new file. With the 295,580 bytes in size but I still get the can't apply patch errors.

Please see attached [https://drive.google.com/file/d/1Y6OS5jj4JMBxEzMnwHfMfhsBOliOEqFz/view?usp=sharing](url)

Thank you,

Andrei

_Originally posted by @B-vR in https://github.com/NVIDIAGameWorks/RTXGI/issues/33#issuecomment-754593450_

**Comment by acmarrs-nvidia** [comment]
Hi @B-vR, sorry you are having problems. A few questions and thoughts:
- Have you modified the files listed in the error message in any way? That could cause this error to happen.
- Are you trying to apply the patch to a repo that already has a previous version of the RTXGI plugin installed? If so, you'll need to remove the previous plugin before trying to apply this patch file. You should revert the engine to [this commit](https://github.com/NvRTX/UnrealEngine/commit/930c11be3557f81c0ae8f749b6462a7d3feab4af) in the NvRTX rtx-dlss-4.26 repository before applying the patch.

**Comment by B-vR** [comment]
I used a clean copy from Git. I just downloaded the branch. I also tried Clone with Sourcetree, same error happend.

I've downloaded the NvRtxGI 4.26 patch from 19.12.2020, and that one worked. The patch was applied, I got no message, neither confirmation or error. I found the plugin in Unreal after compiling and I had the DDGI volume, but it was not working, probes were black.

Thanks

**Comment by acmarrs-nvidia** [comment]
Ah, okay. I think I know what is happening. 

Since the December patch worked for you, you've probably checked out the NvRTX repo with unix style line endings. The line endings in the *new* patch have Windows line endings by default (to solve the problem in issue #33). The mismatch is likely the cause of the problem you are seeing. This means you probably have the opposite problem compared to issue #33. 

An easy way to test this theory is to open the patch file in Notepad++, go to Edit->EOL Conversions, select Unix (LF), save the file, and then try to apply the patch. 

Git tools typically have options that allow you to specify how you want to check out files. For example, in GitExtensions:

![image](https://user-images.githubusercontent.com/7785044/103688622-130ce900-4f60-11eb-9748-7a7159127cd8.png)

You'll want to make sure you are checking out the plugin patch file to have the same format as the engine source files. Basically, checking out "as-is" can be dangerous. So, for example, with GitExtensions you should select the "Checkout Windows-style" option for the code and plugin patch.

**Comment by B-vR** [comment]
Hi,

I've modified the EOL as suggested with Notepad++ but I have the same error. I used git apply -check

V:\UE_426_NvRTX>git apply --check RTXGI-NvRTX4.26.0.patch
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp:2268
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h:32
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp:342
error: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h:14
error: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h: patch does not apply

Maybe my GIT cmd? I downloaded this so that I have git in the CMD - https://git-scm.com/download/win

Thanks,

Andrei

**Comment by B-vR** [comment]
Also, I am trying to apply the patch after I click on setup.bat and get the extra files. And before I compile the engine. Is that ok?

Andrei

**Comment by acmarrs-nvidia** [comment]
> I am trying to apply the patch after I click on setup.bat and get the extra files. And before I compile the engine. Is that ok?

Yep, that should be fine.

I'm not sure how both versions (Windows and Unix line endings) of the plugin patch produce errors - especially given that the December patch works for you. The updated patch file is very similar with only a few small changes. The files that are failing during patch application are engine code, so there must be some incompatibility. The engine changes the patch makes are pretty minor, so at this point you may want to just port in the engine changes directly (instead of using git to apply the patch file).

**Comment by B-vR** [comment]
I figured out what happend. Sort of.

The december patch worked on the repo that I downloaded using the browser - Download ZIP

I just patched that repo with the newest patch file with EOL change in Notepad++ as you said

But. Both the December version, and the newest version of the patch and the newest version + EOL change don't work with the repo that is CLONED with Sourcetree. Even tough the patch file is also CLONED with the same Sourcetree.

As I am not a developer. I don't know.

I am still concerned that the patch did not throw any errors, but it did not say anything either. I am compiling now to see how it works.

![image](https://user-images.githubusercontent.com/76254757/103695298-fba41f00-4fa4-11eb-8ee6-0de1a1290315.png)


Andrei

**Comment by acmarrs-nvidia** [comment]
Okay, it sounds like the issue is related to line endings then. Since there was a mix of source from downloaded zip files and cloned source / patch files, there is potential for format mismatches.

I don't use Sourcetree, but I suggest making sure the application's settings for checkout are set to Windows line endings, then clone both NvRTX and the RTXGI repo. Place the NvRTX plugin patch in the NvRTX root and the patch application should work.

The above result (no warnings or errors) from `git apply` is the expected result.

**Comment by B-vR** [comment]
That sounds great. Thank you. Maybe this info should be added to the documentation so it would be easier for non devs to install this.

Thanks,

Andrei

**Comment by RadAlex** [comment]
Hello,

I do have the same issue with cloned nvrtx-dlss branch (using github
desktop) and patch file, both downloaded yesterday(06 Jan).

PS D:\Github\UnrealEngine-rtx> git apply --check RTXGI-NvRTX4.26.0.patch
error: patch failed:
Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp:272
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp:
patch does not apply
error: patch failed:
Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h:32
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h:
patch does not apply
error: patch failed:
Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp:342
error: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp:
patch does not apply
error: patch failed:
Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h:14
error:
Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h:
patch does not apply
error: patch failed:
Engine/Source/Runtime/Renderer/Private/SystemTextures.h:11
error: Engine/Source/Runtime/Renderer/Private/SystemTextures.h: patch does
not apply


EDIT: 
It seems I got it to apply correctly, by using this command
git apply --reject --whitespace=fix mychanges.patch 

And then checking .rej files and manually add the edits. There was not many of rejected chunks.

Waiting for UE to compile now...

EDIT 2:
Got it working, I can successfully add the GI volume to new project.

Alex.

**Comment by danielnolle** [comment]
Hello,
the notepad ++ EOL change worked I was able to patch without error. 
However, in UE the DDGI volume does not work. 
All probes are black not only the red marked ones.

**Comment by d38s** [comment]
Good day,

Please assist. I was also getting errors when patching, but the _Notepad++ EOL_ change worked, and I checked the repo with errors.
But I still get an error message when I try to patch the plugin:


**D:\UE4xRTXGI>git apply --check RTXGI-NvRTX4.26.0.patch

D:\UE4xRTXGI>git apply RTXGI-NvRTX4.26.0.patch.0.patch
error: can't open patch 'RTXGI-NvRTX4.26.0.patch.0.patch': No such file or directory

D:\UE4xRTXGI>**


![Pathc Failed 3](https://user-images.githubusercontent.com/76823852/103936609-4ef6a880-5130-11eb-922b-b665121b1d61.PNG)

**Comment by Ostagar7** [comment]
Hello every one 

I cloned Nvidia Branch (Unreal Engine 4.26 DLSS) Successfully.

Yet, after I copied (RTXGI-NvRTX4.26.0. patch) in branch root, I tried to install the plugin by 
git apply –check RTXGI-NvRTX4.26.0.patch command in CMD and it showed much error and it did not install the plugin.

Also, I download the RTXGI file again and test it again but the issue remains.
I read almost all the posts on this page, and I found that @RedAlex issue (error message) is the same as mine. But, I don’t understand the way he fixes his issue (what is mychanges.patch, and what .rej file should be check and how should be edited)

//
C. C:\Windows\system32\cmd.exe Microsoft Windows [Version 10.0.19042.685 (c) 2020 Microsoft Corporation. All rights reserved.
C:\Users\PC>E:
E:\>cd E:\UnrealEngine-rtx-dlss-4.26
E:\Unreal Engine-rtx-dlss-4.26>git apply --check RTXGI-NVRTX4.26.0.patch error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: 272 error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: 32, error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: 342 error: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/Ray Tracing/RayTracingLighting.h:14, error: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/SystemTextures.h:11 error: Engine/Source/Runtime/Renderer/Private/SystemTextures.h: patch does not apply

E: Unreal Engine-rtx-dlss-4.26>git apply RTXGI-NVRTX4.26.0. patch RTXGI-NVRTX4.26.0.patch:7: trailing whitespace.
RTXGI-NVRTX4.26.0.patch:8: trailing whitespace.
"FileVersion": 3, RTXGI-NVRTX4.26.0.patch:9: trailing whitespace.
"version": 1, RTXGI-NVRTX4.26.0.patch:10: trailing whitespace.
"VersionName" : "1.1.23", RTXGI-NVRTX4.26.0.patch:11: trailing whitespace.
"FriendlyName" : "NVIDIA RTXGI Plugin", error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: 272 error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: 32, error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: 342 error: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/Ray Tracing/RayTracingLighting.h:14, error: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/SystemTextures.h:11 error: Engine/Source/Runtime/Renderer/Private/SystemTextures.h: patch does not apply
E:\UnrealEngine-rtx-dlss-4.26).

//

I would be grateful to receive your help guys.

**Comment by SlevinSu** [comment]
> Hello,
> the notepad ++ EOL change worked I was able to patch without error.
> However, in UE the DDGI volume does not work.
> All probes are black not only the red marked ones.

Yes,I have got same issuse,did you fix it?

**Comment by RadAlex** [comment]
Hello @Ostagar7 

This is the command you use to apply the patch instead of the documented one. I am sorry, forgot to change the patch filename, it should be the one you use (RTXGI-NvRTX4.26.0 in my case)
git apply --reject --whitespace=fix RTXGI-NvRTX4.26.0.patch

after that search the folder for files with .rej extension, using a text editor (e.g. notepad++), open those rej files and .cpp or .h files with the same name, manually find the lines that needs to be added or altered.

Hope this helps.

Regards,
Alex.
> 
> 
> Hello every one
> 
> I cloned Nvidia Branch (Unreal Engine 4.26 DLSS) Successfully.
> 
> Yet, after I copied (RTXGI-NvRTX4.26.0. patch) in branch root, I tried to install the plugin by
> git apply –check RTXGI-NvRTX4.26.0.patch command in CMD and it showed much error and it did not install the plugin.
> 
> Also, I download the RTXGI file again and test it again but the issue remains.
> I read almost all the posts on this page, and I found that @RedAlex issue (error message) is the same as mine. But, I don’t understand the way he fixes his issue (what is mychanges.patch, and what .rej file should be check and how should be edited)
> 
> //
> C. C:\Windows\system32\cmd.exe Microsoft Windows [Version 10.0.19042.685 (c) 2020 Microsoft Corporation. All rights reserved.
> C:\Users\PC>E:
> E:>cd E:\UnrealEngine-rtx-dlss-4.26
> E:\Unreal Engine-rtx-dlss-4.26>git apply --check RTXGI-NVRTX4.26.0.patch error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: 272 error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: 32, error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: 342 error: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/Ray Tracing/RayTracingLighting.h:14, error: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/SystemTextures.h:11 error: Engine/Source/Runtime/Renderer/Private/SystemTextures.h: patch does not apply
> 
> E: Unreal Engine-rtx-dlss-4.26>git apply RTXGI-NVRTX4.26.0. patch RTXGI-NVRTX4.26.0.patch:7: trailing whitespace.
> RTXGI-NVRTX4.26.0.patch:8: trailing whitespace.
> "FileVersion": 3, RTXGI-NVRTX4.26.0.patch:9: trailing whitespace.
> "version": 1, RTXGI-NVRTX4.26.0.patch:10: trailing whitespace.
> "VersionName" : "1.1.23", RTXGI-NVRTX4.26.0.patch:11: trailing whitespace.
> "FriendlyName" : "NVIDIA RTXGI Plugin", error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: 272 error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: 32, error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: 342 error: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/Ray Tracing/RayTracingLighting.h:14, error: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h: patch does not apply error: patch failed: Engine/Source/Runtime/Renderer/Private/SystemTextures.h:11 error: Engine/Source/Runtime/Renderer/Private/SystemTextures.h: patch does not apply
> E:\UnrealEngine-rtx-dlss-4.26).
> 
> //
> 
> I would be grateful to receive your help guys.

**Comment by Ostagar7** [comment]
Hello
First, thank you @RedAlex for your guidance. 
To be honest, I have done the first part (CMD: git apply – reject –whitespace=fix RTXGI-NvRTX4.26.0. patch) and I had received numerous errors:

// After second time, just to show errors at end part //
//
RTXGI-NvRTX4.26.0.patch:8: trailing whitespace.
        "FileVersion": 3,
RTXGI-NvRTX4.26.0.patch:9: trailing whitespace.
        "Version": 1,
RTXGI-NvRTX4.26.0.patch:10: trailing whitespace.
        "VersionName": "1.1.23",
RTXGI-NvRTX4.26.0.patch:11: trailing whitespace.
        "FriendlyName": "NVIDIA RTXGI Plugin",
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/RTXGI.uplugin...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/RTXGI.uplugin: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/ApplyLightingDeferred.usf...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/ApplyLightingDeferred.usf: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/ProbeUpdateRGS.usf...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/ProbeUpdateRGS.usf: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/ProbeViewRGS.usf...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/ProbeViewRGS.usf: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/Common.ush...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/Common.ush: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/DDGIVolumeDefines.ush...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/DDGIVolumeDefines.ush: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/Irradiance.ush...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/Irradiance.ush: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeBlendingCS.usf...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeBlendingCS.usf: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeBorderUpdateCS.usf...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeBorderUpdateCS.usf: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeCommon.ush...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeCommon.ush: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeRelocationCS.usf...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeRelocationCS.usf: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeStateClassifierCS.usf...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDK/ddgi/ProbeStateClassifierCS.usf: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDKDefines.ush...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/SDKDefines.ush: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/VisualizeDDGIProbes.usf...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Shaders/Private/VisualizeDDGIProbes.usf: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIBlueprintLibrary.cpp...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIBlueprintLibrary.cpp: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolume.cpp...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolume.cpp: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolumeComponent.cpp...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolumeComponent.cpp: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolumeUpdate.cpp...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolumeUpdate.cpp: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolumeUpdate.h...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolumeUpdate.h: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolumeVisualize.cpp...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/DDGIVolumeVisualize.cpp: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/RTXGIPlugin.cpp...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/RTXGIPlugin.cpp: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/RTXGIPluginSettings.cpp...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/RTXGIPluginSettings.cpp: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/RTXGIPluginSettings.h...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Private/RTXGIPluginSettings.h: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Public/DDGIBlueprintLibrary.h...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Public/DDGIBlueprintLibrary.h: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Public/DDGIVolume.h...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Public/DDGIVolume.h: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Public/DDGIVolumeComponent.h...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Public/DDGIVolumeComponent.h: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Public/RTXGIPlugin.h...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/Public/RTXGIPlugin.h: already exists in working directory
Checking patch Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/RTXGI.Build.cs...
error: Engine/Plugins/Runtime/Nvidia/RTXGI/Source/RTXGI/RTXGI.Build.cs: already exists in working directory
Checking patch Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp...
error: while searching for:
?
CSV_DEFINE_CATEGORY(LightCount, true);?
?
const TCHAR* GetDepthPassReason(bool bDitheredLODTransitionsUseStencil, EShaderPlatform ShaderPlatform)?
{?
        if (IsForwardShadingEnabled(ShaderPlatform))?

error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp:272
Hunk #2 succeeded at 1225 (offset -27 lines).
Hunk #3 succeeded at 2269 (offset -27 lines).
Hunk #4 succeeded at 2913 (offset -27 lines).
Hunk #5 succeeded at 2928 (offset -27 lines).
Checking patch Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h...
Checking patch Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp...
Checking patch Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h...
Checking patch Engine/Source/Runtime/Renderer/Private/SystemTextures.h...
Applying patch Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp with 1 reject...
Rejected hunk #1.
Hunk #2 applied cleanly.
Hunk #3 applied cleanly.
Hunk #4 applied cleanly.
Hunk #5 applied cleanly.
Applied patch Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h cleanly.
Applied patch Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp cleanly.
Applied patch Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h cleanly.
Applied patch Engine/Source/Runtime/Renderer/Private/SystemTextures.h cleanly.
//

And I have found DeferredShadingRenderer, IndirectLightRendering, RayTracingLighting, and SystemTextures (.rej, .h, and .cpp) files, yet I do not know how to change and what needed to be changed (even by considering the line marked in the error list), and I do not have coding skill/knowledge to fix this Issue.
Hence, I would be grateful to receive your help with this issue

**Comment by acmarrs-nvidia** [comment]
Hi @Ostagar7 - you don't need to modify the git commands from the documentation. This is an unfortunate consequence of the line ending settings from when the engine and RTXGI plugin code was checked out on your machine.

I wrote a [UE4 Getting Started Guide](https://github.com/NVIDIAGameWorks/RTXGI/wiki/UE4-Plugin-Getting-Started-Guide) in the wiki section that will hopefully help you get up and running.
