### ISSUE TITLE
UE 4.26 all probes are black

### ISSUE THREAD

**Issue by danielnolle** [NVIDIAGameWorks/RTXGI-DDGI#36]
Hello,
I have loaded the default UE exterior archviz scene and placed the ddgi volume there. I have enabled ddgi by cvar but all probes are black when I view them. Normally it should work automatically when I put the ddgi volume in a scene where raytracing is enabled. 

probeviz says that the geometry is green so it should work there too. 

I had problems before applying the patch. With the notepad ++ SOL switch to Unix, the whole thing worked. Can that have caused the error?

**Comment by acmarrs-nvidia** [comment]
Hi @gonnerman, sorry you are running into problems. The line endings issue should not affect the plugin's functionality. 

Check the RTXGI plugin settings (Project Settings->RTXGI->Irradiance Bits). See the first image below.

- Are your volumes set up for 32-bit or 16-bit irradiance? If light sources use very bright values *and* the volumes are set to 16-bits, the Irradiance Scalar field needs to be adjusted to account for the bright lights (so set this to a value between 0.f and 1.f).
- Depending on the state of your project before the new plugin version was installed, you may need to cycle between 32-bit and 16-bit irradiance to clear the probes.

 

![image](https://user-images.githubusercontent.com/7785044/103927424-52664180-50e8-11eb-9860-6d95b9ec4d1e.png)

![image](https://user-images.githubusercontent.com/7785044/103927592-978a7380-50e8-11eb-9b54-87dc032af703.png)

**Comment by d38s** [comment]
> Hi @gonnerman, sorry you are running into problems. The line endings issue should not affect the plugin's functionality.
> 
> Check the RTXGI plugin settings (Project Settings->RTXGI->Irradiance Bits). See the first image below.
> 
> * Are your volumes set up for 32-bit or 16-bit irradiance? If light sources use very bright values _and_ the volumes are set to 16-bits, the Irradiance Scalar field needs to be adjusted to account for the bright lights (so set this to a value between 0.f and 1.f).
> * Depending on the state of your project before the new plugin version was installed, you may need to cycle between 32-bit and 16-bit irradiance to clear the probes.
> 
> ![image](https://user-images.githubusercontent.com/7785044/103927424-52664180-50e8-11eb-9860-6d95b9ec4d1e.png)
> 
> ![image](https://user-images.githubusercontent.com/7785044/103927592-978a7380-50e8-11eb-9b54-87dc032af703.png)

Good day,
Please assist, my probes are also black and the DDGI Volume is not activating any light bounces.
![DDGI Fail](https://user-images.githubusercontent.com/76823852/103955410-e23ed680-514e-11eb-9ccc-082ce04c0c48.PNG)

**Comment by danielnolle** [comment]
ah thanks. 
That was indeed the problem. I'm only surprised that the PBR approach with the correct luminous intensity of the sun is virtually too much. 

Could be in the documentation that the new sunsky system is too much for RTXGI.

**Comment by acmarrs-nvidia** [comment]
> Could be in the documentation that the new sunsky system is too much for RTXGI.

RTXGI can represent the irradiance values of the sun/sky system without a problem. When you select the 16-bit irradiance format we compress radiance values to fit into the smaller data format (resulting in substantial memory savings). The tradeoff is a bit more manual work (setting up the irradiance scalar) in exchange for the saved memory.

**Comment by d38s** [comment]
Good day,

Please assist, my probes are coming out **black**, and the DDGI Volume is essentially not working.
Any ideas?

![DDGI Fail - Copy](https://user-images.githubusercontent.com/76823852/104086522-62edf780-5261-11eb-9423-d35af913d7ab.PNG)

**Comment by SlevinSu** [comment]
Yes,today I'm got the same problem with you guys too.
Anyone can fix it ?Thanks.

**Comment by d38s** [comment]
> Yes,today I'm got the same problem with you guys too.
> Anyone can fix it ?Thanks.

Unfortunately no fix yet. Hoping an official response.

**Comment by acmarrs-nvidia** [comment]
Hi @d38s & @SlevinSu. A few thoughts below:
- Make sure you are running UE4 in DX12 mode. The easy way to do this is to set the project's default RHI to DirectX 12.
- Make sure you are running UE4 with Ray Tracing enabled. RT should show as checked in the project settings.
- Make sure RTXGI is enabled. On the console, use `r.RTXGI.DDGI 1` to enable RTXGI.

![image](https://user-images.githubusercontent.com/7785044/104199649-af6a3c00-53f5-11eb-8f42-87dc57b84caa.png)
![image](https://user-images.githubusercontent.com/7785044/104199543-9497c780-53f5-11eb-9c54-41ac481687ec.png)

**Comment by SlevinSu** [comment]
Thanks for this so much,I just Run with DX12,but missed the Ray Tracing!that the key.
Yeah,I'm follow the vidieo on Youtube,that's a big mistake.


Thanks ag.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVIDIAGameWorks/RTXGI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 晚上11:16
收件人:&nbsp;"NVIDIAGameWorks/RTXGI"<RTXGI@noreply.github.com&gt;;
抄送:&nbsp;"宬锐"<45299740@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NVIDIAGameWorks/RTXGI] UE 4.26 all probes are black (#36)





 
Hi @d38s &amp; @SlevinSu. A few thoughts below:
  
Make sure you are running UE4 in DX12 mode. The easy way to do this is to set the project's default RHI to DirectX 12.
 
Make sure you are running UE4 with Ray Tracing enabled. RT should show as checked in the project settings.
 
Make sure RTXGI is enabled. On the console, use r.RTXGI.DDGI 1 to enable RTXGI.

**Comment by d38s** [comment]
> Hi @d38s & @SlevinSu. A few thoughts below:
> 
> * Make sure you are running UE4 in DX12 mode. The easy way to do this is to set the project's default RHI to DirectX 12.
> * Make sure you are running UE4 with Ray Tracing enabled. RT should show as checked in the project settings.
> * Make sure RTXGI is enabled. On the console, use `r.RTXGI.DDGI 1` to enable RTXGI.
> 
> ![image](https://user-images.githubusercontent.com/7785044/104199649-af6a3c00-53f5-11eb-8f42-87dc57b84caa.png)
> ![image](https://user-images.githubusercontent.com/7785044/104199543-9497c780-53f5-11eb-9c54-41ac481687ec.png)

Thanks for reply.
Probes are still black. DDGI Volume not working.

**Comment by acmarrs-nvidia** [comment]
@d38s I'll need more information about how things are not working in order to help.

**Comment by d38s** [comment]
Hi, the issue, as mentioned above is that the DDGIVolume is not working as expected when I drag it into the scene. The probes are all black and are not generating any bounce light.

I followed all the instruction from the documentation:

- I built my NvRTX 4.26.0 
- Installed the RTXGI plugin, Patched it
- Setup, project's default RHI to DirectX 12
- Enabled Ray Tracing
- Enabled the RTXGI plugin. (on the console, use r.RTXGI.DDGI 1)

Once I placed the DDGIVolume actors in the scene, there's no raytracing.


> @d38s I'll need more information about how things are not working in order to help.

**Comment by d38s** [comment]
> @d38s I'll need more information about how things are not working in order to help.

Hi, any feedback from the information I gave?

**Comment by acmarrs-nvidia** [comment]
Can you confirm that other ray traced effects are working? (e.g. attach a screenshot of the debug mode that shows the ray traced barycentrics).

**Comment by d38s** [comment]
> Can you confirm that other ray traced effects are working? (e.g. attach a screenshot of the debug mode that shows the ray traced barycentrics).
![OutPut Log_Debug_A001](https://user-images.githubusercontent.com/76823852/106943084-a0915380-672d-11eb-9dc6-18ed391ff8dd.PNG)
[RTXGI_Project_A001_2.log](https://github.com/NVIDIAGameWorks/RTXGI/files/5927966/RTXGI_Project_A001_2.log)

**Comment by d38s** [comment]
> Can you confirm that other ray traced effects are working? (e.g. attach a screenshot of the debug mode that shows the ray traced barycentrics).

Hi, I have attached a snap shot of my output log and a text document of the output log. Honestly, I cannot confirm if other raytracing effects work because it doesnt seem like anyhting works. not sure where or what raytraced barycentrics are. I hope you can find that in the debug log document.

![OutPut Log_Debug_A002](https://user-images.githubusercontent.com/76823852/106943824-94f25c80-672e-11eb-8624-608ceef096fa.PNG)

**Comment by d38s** [comment]
> Can you confirm that other ray traced effects are working? (e.g. attach a screenshot of the debug mode that shows the ray traced barycentrics).


**Please let me know if the information prived helps  ????????**

**Comment by acmarrs-nvidia** [comment]
You can confirm if ray tracing is working by using the debug visualization modes. If these debug modes do not exist, ray tracing is not enabled. If you don't see output (like below) when selecting the "barycentrics" option, ray tracing isn't working and you have a problem that is not related to RTXGI.

![image](https://user-images.githubusercontent.com/7785044/107439998-ed47a680-6b00-11eb-968b-ca7ceea21f4a.png)

**Comment by acmarrs-nvidia** [comment]
Have you resolved your issue?
