### ISSUE TITLE
Disabling collision on DDGI Volume Component

### ISSUE THREAD

**Issue by bhillVelan** [NVIDIAGameWorks/RTXGI-DDGI#37]
When I add a DDGI Volume Component to my FPS template in Unreal they are being treated as colliders for my projectiles.  Is there some way to disable their collision?

**Comment by scragnog** [comment]
I had this same issue, and it looks like there's no direct way in-engine to set the collision channels for the DDGI volumes.
The only workaround I was able to find (and this is far from a solution) was to edit the trace for the projectiles, and add all DDGI volumes (getting the references on begin play and adding into an array variable) and add the array of volumes into the 'ignore actor' list for the trace.
It works, but it's far from ideal.

**Comment by acmarrs-nvidia** [comment]
Thanks for reporting this issue. It is now fixed.
