### ISSUE TITLE
Having an Issue applying the Nvidia RTX GI patch

### ISSUE THREAD

**Issue by malochen** [NVIDIAGameWorks/RTXGI-DDGI#38]
E:\Nvidia_Branch>git apply RTXGI-NvRTX4.26.0.patch
RTXGI-NvRTX4.26.0.patch:7: trailing whitespace.
{
RTXGI-NvRTX4.26.0.patch:8: trailing whitespace.
        "FileVersion": 3,
RTXGI-NvRTX4.26.0.patch:9: trailing whitespace.
        "Version": 1,
RTXGI-NvRTX4.26.0.patch:10: trailing whitespace.
        "VersionName": "1.1.23",
RTXGI-NvRTX4.26.0.patch:11: trailing whitespace.
        "FriendlyName": "NVIDIA RTXGI Plugin",
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp:272
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h:32
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp:342
error: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h:14
error: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/SystemTextures.h:11
error: Engine/Source/Runtime/Renderer/Private/SystemTextures.h: patch does not apply

**Comment by malochen** [comment]
Hi everyone, I am trying to get Nvidias RTX Global Illumination Plugin running.

I cloned their branch of the UE4 Build and downloaded the appropriate version of the patch for their 4.26.0.

However, whenever I copy the patch into the root directory and enter the "git apply" command in CMD the patch fails to install properly.

I would be incredibly thankful for any advise

**Comment by mesfeir** [comment]
I had the same issue. Broke my head around it for a day. Finally, I resolved it by using the git command line instead of command prompt.

**Comment by malochen** [comment]
> I had the same issue. Broke my head around it for a day. Finally, I resolved it by using the git command line instead of command prompt.


Hello buddy, I have found a solution to the problem    this ——https://github.com/NVIDIAGameWorks/RTXGI/issues/35

**Comment by malochen** [comment]
> I had the same issue. Broke my head around it for a day. Finally, I resolved it by using the git command line instead of command prompt.

Hope it helps you
