### ISSUE TITLE
RTXGI-NvRTX4.26.0.patch does not apply successfully on the rtx-dlss-4.26.1 source

### ISSUE THREAD

**Issue by rohanbam** [NVIDIAGameWorks/RTXGI-DDGI#39]
$ git apply --check RTXGI-NvRTX4.26.0.patch
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp:2268
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply

Is this expected until there is a 4.26.1 version of the patch or should it have worked?

**Comment by acmarrs-nvidia** [comment]
A 4.26.1 patch will be released soon, but the 'does not apply' behavior is most likely not related to the engine patch version. See the [UE4 Plugin Getting Started Guide](https://github.com/NVIDIAGameWorks/RTXGI/wiki/UE4-Plugin-Getting-Started-Guide) and Issue #35

**Comment by acmarrs-nvidia** [comment]
The [UE4.26.1 plugin patch](https://github.com/NVIDIAGameWorks/RTXGI/blob/main/ue4-plugin/RTXGI-NvRTX4.26.1.patch) is now live, please use that patch file instead.

There were some small engine code changes in 4.26.1, so the 4.26.0 patch is *not* compatible with 4.26.1.

**Comment by rohanbam** [comment]
Yes, Thank you. :)
