### ISSUE TITLE
Patch error on 4.26.1 How to solve and apply correctly the patch?

### ISSUE THREAD

**Issue by dnmorato** [NVIDIAGameWorks/RTXGI-DDGI#40]
Hi!
Everytime I apply the pathc check, I get this errors.

Any Idea how to solve this?

B:\Unreal>git apply --check RTXGI-NvRTX4.26.1.patch
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp:272
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h:32
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp:342
error: Engine/Source/Runtime/Renderer/Private/IndirectLightRendering.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h:14
error: Engine/Source/Runtime/Renderer/Private/RayTracing/RayTracingLighting.h: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/SystemTextures.h:11
error: Engine/Source/Runtime/Renderer/Private/SystemTextures.h: patch does not apply

**Comment by Brujah88** [comment]
I get the same error, it's really hard to get it working apparently.

**Comment by cgabdel** [comment]
Yes, same error, no way to get around it.

**Comment by dnmorato** [comment]
Alright! I actually solved it! Here is how I did it:

instead of downloading the zip files from github, I cloned both repositories.

Here is how to do it. On the repository, just copy the link. Then, on your pc, right click on the browser and using git GUI, clone the repository.

After doing this, all errors are gone when using git apply --check...

**Comment by acmarrs-nvidia** [comment]
This is a duplicate of #35.

How to properly clone UE4, the RTXGI SDK, and apply the patch is covered in the [UE4 Getting Started Guide](https://github.com/NVIDIAGameWorks/RTXGI/wiki/UE4-Plugin-Getting-Started-Guide).
