### ISSUE TITLE
RTXGI in reflections

### ISSUE THREAD

**Issue by pidnee** [NVIDIAGameWorks/RTXGI-DDGI#44]
The GI seems strange/dark in reflections. I know raytraced reflections have issues with transparent objects too (they go black).

Here is a shot looking at a mirror.

![image](https://user-images.githubusercontent.com/4676641/111390284-98520e00-8706-11eb-925d-a25b5e80c7d7.png)

Here is how what is being reflected looks.

![image](https://user-images.githubusercontent.com/4676641/111390393-bfa8db00-8706-11eb-9d2c-958a36e668ad.png)

Currently we are fudging all the internal lighting by using emissive hidden objects (as per the documentation) until we can get RTXDI. 

![image](https://user-images.githubusercontent.com/4676641/111390517-f8e14b00-8706-11eb-9111-e2d4988277e3.png)

They can be seen in the reflections also (even though they are hidden objects) which I assume is also a result of the RTXGI not being happy with reflections.

**Comment by pidnee** [comment]
https://github.com/NVIDIAGameWorks/RTXGI/issues/27

I just saw this. I guess its a long way off still :(

**Comment by acmarrs-nvidia** [comment]
Correct, RTXGI in reflections is not currently supported. Stay tuned.
