### ISSUE TITLE
I get "modules are missing" after patch succesfully applied with no erros 

### ISSUE THREAD

**Issue by bats11** [NVIDIAGameWorks/RTXGI-DDGI#47]
![Screenshot (48)](https://user-images.githubusercontent.com/70653789/112063357-930b1e00-8b61-11eb-876c-9c88df2a7d8e.png)

**Comment by acmarrs-nvidia** [comment]
Need more information in order to help. Did you apply the correct plugin patch to the version of the engine you are using? What engine version are you using?

**Comment by bats11** [comment]
Hi! I just tried to do everything again for double checking but I got the
same result.

I used the unreal version downloaded from this link a couple of ours ago:
https://github.com/NvRTX/UnrealEngine
which works fine, than I made the EOL Conversions Unix (LF) to the
RTXGI-NvRTX4.26.1.patch founded on this link:
https://github.com/NVIDIAGameWorks/RTXGI
and applied it with no error messages but it still say the same


Il giorno mar 23 mar 2021 alle ore 00:01 Adam Marrs <
***@***.***> ha scritto:

**Comment by bats11** [comment]
maybe I need to try with this version?
https://github.com/NvRTX/UnrealEngine/releases/tag/nvrtx-4.26.1-2


Il giorno mar 23 mar 2021 alle ore 03:08 Alessandro Batacchioli <
***@***.***> ha scritto:

**Comment by bats11** [comment]
no way. i tried even with the engine version UnrealEngine-nvrtx-4.26.1-2
and the nvrtx4.26.1 patch but I get always to the same result

Il giorno mar 23 mar 2021 alle ore 03:12 Alessandro Batacchioli <
***@***.***> ha scritto:

**Comment by tiont** [comment]
Hi @bats11 . Since this issue was originally reported back in March, we've released a binary version of the RTXGI plugin for UE4 4.27. You can find it [here](https://developer.nvidia.com/rtxgi-sdk-get-started#ue4-latest-version). This should remove the patch application step that was necessary in previous versions.

Please give the latest version a try and let us know if you run into any further issues.

**Comment by bats11** [comment]
Thank you...

Il mar 16 nov 2021, 17:29 tiont ***@***.***> ha scritto:
