### ISSUE TITLE
Add Visual C++ ATL to system requirements

### ISSUE THREAD

**Issue by ghost** [NVIDIAGameWorks/RTXGI-DDGI#5]
`samples/test-harness/src/common/Shaders.cpp` includes `<atlcomcli.h>` which I did not have installed. Would be nice to have it included in the system requirements. This was easy to fix; from Visual Studio Installer, choose Modify > Individual Components and scroll down and choose Visual C++ ATL that's appropriate for your architecture (x86 and x64 for me).

**Comment by acmarrs-nvidia** [comment]
Good suggestion, I'll change this.

**Comment by acmarrs-nvidia** [comment]
Visual C++ ATL is [now included](https://github.com/NVIDIAGameWorks/RTXGI/commit/18a35b1ac87d9bf3f35dabf332feb0187737b0f0) in the system requirements in the README and documentation.
