### ISSUE TITLE
Nvrtx_caustics-4.26 branch patch error

### ISSUE THREAD

**Issue by nothingre** [NVIDIAGameWorks/RTXGI-DDGI#51]
I cloned the nvrtx_caustics4.26 branch following the instructions for getting started and encountered an error checking compatibility.
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp:272
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.cpp: patch does not apply
error: patch failed: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h:32
error: Engine/Source/Runtime/Renderer/Private/DeferredShadingRenderer.h: patch does not apply

I cloned rtx_dlss_4.26.1 and installed RTXGI without any problem

**Comment by acmarrs-nvidia** [comment]
The NvRTX Caustics branch is not compatible with the v1.1.23 RTXGI UE4 plugin patches.
