### ISSUE TITLE
Console Variables not working

### ISSUE THREAD

**Issue by Markgundam** [NVIDIAGameWorks/RTXGI-DDGI#52]
I've downloaded the NvRTX branch with the RTXGI plugin pre-installed and built using Visual Studio 2019. Setup seems to work, DDGI plugin was found and ray tracing was turned on in a new project. I've set up a simple scene and dragged the DDGI Volume but nothing happens. I've turned on DDGI via the console variable .r.RTX.DDGI 1 and still nothing. All the other console variables also do nothing. What would cause for this to happen?

**Comment by acmarrs-nvidia** [comment]
Hi @Markgundam, have you also set the new engine side `r.GlobalIllumination.ExperimentalPlugin` cvar?

![image](https://user-images.githubusercontent.com/7785044/114867488-e10eec80-9dc2-11eb-94c0-f6549420b7e4.png)

**Comment by Markgundam** [comment]
Yeah now it's working! Had no idea this documentation existed since I've downloaded the branch with the plugin pre-installed. Found the document under the RTXGI SDK plugin. Many thanks!

**Comment by acmarrs-nvidia** [comment]
Good to hear! This documentation is also included with the RTXGI plugin in the NvRTX branch where the plugin is pre-installed.

https://github.com/NvRTX/UnrealEngine/tree/rtx-dlss-4.26/Engine/Plugins/Runtime/Nvidia/RTXGI/README.md
