### ISSUE TITLE
Is there a way we can install rtxgi into caustics branch

### ISSUE THREAD

**Issue by manikantagamer** [NVIDIAGameWorks/RTXGI-DDGI#53]
the demo from below link, the artist used RTXGI V2 + Caustics version
https://www.artstation.com/artwork/nYGNRr

can any one let me know how to merge caustics version with RTXGI branch, as I am not a programmer

**Comment by tiont** [comment]
Hi @manikantagamer, 

Our latest caustics NvRTX branch includes RTXGI plugin. Please find the latest 4.27 Caustics branch on Github here: [https://github.com/NvRTX/UnrealEngine/tree/NvRTX_Caustics-4.27]

For more details on our NvRTX branches including how to get access to the source repo, please refer to this page here: [https://developer.nvidia.com/unrealengine]

**Comment by tiont** [comment]
Closing
