### ISSUE TITLE
RTXGI Unity Example Project?

### ISSUE THREAD

**Issue by smootler** [NVIDIAGameWorks/RTXGI-DDGI#54]
Is the project shown [in this presentation](https://www.youtube.com/watch?v=F3hIculYFwM) available anywhere? Even if outdated, it would be highly useful as a starting point for a C#/Unity integration.

**Comment by acmarrs-nvidia** [comment]
Hi @smootler - unfortunately, no that project is not available. RTXGI is not yet supported in Unity.

**Comment by smootler** [comment]
@acmarrs-nvidia Any eta?

**Comment by tiont** [comment]
Hi @smootler. No there is no ETA for Unity integration at this time. However, it is something that we are investigating and hope to have an update on in the future. Please stay tuned.

**Comment by kristian15959** [comment]
Hello, got few questions about this topic.
What do you mean by RTXGI not being supported? @acmarrs-nvidia 
Is there some custom API that RTXGI uses that does not work with Unity? as I guess RTXGI is still built on DXR right?

This is my own ProbeVolume using DX12 DXR in URP 2021.2 and it works on GTX 1070. Full Irradiance map and Occlusion map.
![image](https://user-images.githubusercontent.com/8007327/148981697-75086d65-c559-46d0-b8a7-0370d16d1c83.png)

![image](https://user-images.githubusercontent.com/8007327/148982800-2f83d96a-0a73-41d7-bc64-7e47f033c842.png)

**Comment by acmarrs-nvidia** [comment]
> What do you mean by RTXGI not being supported?

I mean that RTXGI is not natively implemented in Unity or provided as an engine plugin. At this point in time, you could certainly implement RTXGI's DDGI algorithm using Unity's DXR implementation yourself though!
