### ISSUE TITLE
UE4 - Critical - RTXGI breaks if any static mesh is set to a lighting channel other than 0

### ISSUE THREAD

**Issue by scragnog** [NVIDIAGameWorks/RTXGI-DDGI#56]
I've been running into an issue with my project using RTXGI that's taken a while to debug.
I was noticing that the effect of RTXGI would turn on/off depending on where I looked in my scene either in editor or during play.

This appears to be caused by having a static mesh in the viewport that's set to a lighting channel other than 0 (or even just having Channel 0 unchecked.). Once this is set, all effect of the DDGI Volume become disabled, even on other meshes in the scene.
Moving the offending mesh out of the viewport by rotating the camera brings back the RTXGI effect.

Steps to reproduce -
- Load RTXGITest Project
- set any static mesh in the scene to use lighting channel 1, or remove channel 0, or any combination other than just Channel 0
- Move the camera around so the above mesh moves in and out of the viewport

I should add that I've used previous iterations of RTXGI (this is the 4.27.1 plugin currently) that did not have this issue.

**Comment by MartianDays** [comment]
Hey bud,

I’m certain I’ve encountered this bug before. I *think* there is indeed a fix too. Perhaps look for my tickets in here? Might find what you need.

I’d look myself, but I’ve only got a few seconds here to respond atm.

Otherwise I think either @acmarrs-nvidia or @Atrix256 helped me resolve this once?

Maybe post a video of the issue just in case too!

All the best!

**Comment by scragnog** [comment]
Thanks mate. I've had a look and I can't seem to spot any solutions to this.
I can see that 2 other users have reported the same issue on the Questions for the plugin on the UE4 Marketplace, but no responses there it seems.

**Comment by tiont** [comment]
Thanks for reporting this @scragnog. We did notice the question on the marketplace as well and are working to investigate the issue. We will report back once we have more info on the issue and it's resolution.

**Comment by scragnog** [comment]
> Thanks for reporting this @scragnog. We did notice the question on the marketplace as well and are working to investigate the issue. We will report back once we have more info on the issue and it's resolution.

Much appreciated!

**Comment by pmorley-nv** [comment]
@scragnog could you please send a video of the issue?  I am setting walls in the cornell box to lighting channel 1 and moving the camera and unable to reproduce it.

**Comment by scragnog** [comment]
Hi,

of course, please see the following - https://www.dropbox.com/s/dvq1837p11cqkat/Desktop%202021.11.02%20-%2020.36.09.02.mp4?dl=0

**Comment by scragnog** [comment]
I should add, and this may or may not be related, but adjusting the Lighting Channels on the DDGI Volume has no effect whatsoever. the GI always affects Lighting Channel 0 (and perhaps all others, but I can't confirm because GI fails when any mesh in the scene uses anything other than Lighting Channel 0) regardless of what is set on the volume.

**Comment by pmorley-nv** [comment]
I'm still unable to reproduce on my end with a RTX 3080.  What GPU are you using?

**Comment by scragnog** [comment]
RTX 3090. Latest GameReady Drivers. Windows 10. Stock UE4.27 and the RTXGI Plugin linked from the UE Marketplace.

I'm trying to think if there's anything else unique to my setup here, but I can't think of much.
I am using multi-monitor, and one of those monitors is using HDR in Windows, but I run UE on a different display.

**Comment by pmorley-nv** [comment]
ok thank you for all the information.  It's possible the issue is fixed but not pushed out to the public.  I'll pull down the public version to see if I can reproduce it.

**Comment by pmorley-nv** [comment]
we found the issue and it will be fixed in the next release.  Thanks for your help.
