### ISSUE TITLE
RESTIR with DDGI?

### ISSUE THREAD

**Issue by wangyuehi** [NVIDIAGameWorks/RTXGI-DDGI#57]
Hi,

I wonder if the RESTIR implementation (siggraph 2021, [Dynamic Diffuse Global Illumination Resampling ](https://arxiv.org/pdf/2108.05263.pdf)) will be supported, or in your plan of being supported?

Would be great to be able to toggle on and off to see the result, even if it's an naive implementation, not production ready.

Thanks,
Yue

**Comment by LeonBrands** [comment]
ReSTIR is implemented in the RTXDI api - if you have access to that repository take a look over there, their latest sample integrates RTXGI

**Comment by wangyuehi** [comment]
Thanks for the reply!
No I wasn't aware of that repo, I have requested access, will take a look  :)
