### ISSUE TITLE
UE5 support?

### ISSUE THREAD

**Issue by snowzhangy** [NVIDIAGameWorks/RTXGI-DDGI#58]
Hi. I'm currently working on UE5 EA version. Is there any plan to update the RTXGI to UE5?
thank you

**Comment by oscarbg** [comment]
+1

**Comment by tiont** [comment]
Hi @snowzhangy and @oscarbg,

Yes we are investigating adding support for UE5 but do not have any concrete plans to share at this time. Please stay tuned for future updates as we approach UE5's launch date.

Regards,
Tion Thomas
