### ISSUE TITLE
I didnt know how it works

### ISSUE THREAD

**Issue by Manuelsnake** [NVIDIAGameWorks/RTXGI-DDGI#6]
Could anyone tell me how to make that work on my Gtx 1080 i download the file but i cant use it in Cmake, is there any video or image for help me?
Thanks Everyone

**Comment by Nickelium** [comment]
I don`t know about the specifics for cards without RT cores but normally it is pretty much the same as described in the readme (https://github.com/NVIDIAGameWorks/RTXGI/blob/master/README.md#getting-started)

**Comment by Manuelsnake** [comment]
i install all the System Requirements
Windows 10 v1809 or higher
Windows 10 SDK version 10.0.17763 or higher
CMake 3.15 or higher
Visual Studio 2017 or 2019
Latest graphics driver
Any DXR enabled GPU. NVIDIA DXR enabled GPUs:
RTX 2080 Ti, 2080 SUPER, 2080, 2070 SUPER, 2070, 2060 SUPER, 2060
GTX 1660 Ti, 1660 SUPER, 1660
GTX 1080 Ti, 1080, 1070, 1060 6GB (or higher)

 but Cmake Doesn't work maybe i dont know how to use it, but i follow all the passage, did you have any video or picture can help me?

**Comment by SirKnightTG** [comment]
Here is what my cmake looks like that works:
![cmake](https://user-images.githubusercontent.com/7001777/79075793-824bfa00-7cba-11ea-9352-b872b6e894e1.jpg)

So the top most field should be where the RTXGI samples source is (the library and an application with a simple path tracer is located there), the second is where you want the generated project files to be, in my case RTXGI\samples\build

Then click Configure, then Generate. After this, your sln file should be in "build."

**Comment by acmarrs-nvidia** [comment]
@Manuelsnake, instructions on how to use CMake are in the "Quick Start" section of the documentation (available in docs/manual/QuickStart.html of the SDK distro). This includes images of CMake and the paths you should use. 

Thanks @SirKnightTG, your response is correct and helpful too.
