### ISSUE TITLE
DDGIResetScrolledPlane 

### ISSUE THREAD

**Issue by jirzynek** [NVIDIAGameWorks/RTXGI-DDGI#62]
Hi,

I have been experimenting with the scrolling volumes and I have noticed strange behaviour, I'm not sure if this is intended. 

I have included some animations showing the problem. 

Scrolling the probes to the right:
![bl0](https://user-images.githubusercontent.com/7784878/161046216-880de39b-6b23-4f5f-bde4-1d6b8439390f.gif)
Scrolling the probes to the left:
![bad_left](https://user-images.githubusercontent.com/7784878/161051133-2a16a1c8-b48b-453b-8b5b-b6638985577a.gif)

This animation was created with the following:
- 6 x 1 x 1 volume,
- shader modification in `DDGIResetScrolledPlane` that writes random colour into irradiance texture every time a probe needs to be reset - this helps to visualise the problem
- slowly scrolling probes to the right/left

Also, if the probes are scrolled too quickly, scrolling code on cpu side can go wrong and miss a few probes
![quick_scroll](https://user-images.githubusercontent.com/7784878/161051474-ae249a0c-b6fa-4590-86a5-c6012433777a.png)

Normally I would expect something like this (with my local fix):
Scrolling the probes to the right:
![ok_right](https://user-images.githubusercontent.com/7784878/161050524-30e1c6b1-8149-44d5-9fe1-15ffb387255e.gif)

Scrolling the probes to the left:
![ok_left](https://user-images.githubusercontent.com/7784878/161051324-0a65c063-90d0-478e-8a6f-bf8dd6e1355c.gif)

Python code showing the problem and the fix:

```python
probe_count = 6

def f(offset):
    # DDGI calculations (DDGIResetScrolledPlane)
    if offset > 0:
        v = math.fmod(offset, probe_count) - 1
    else:
        v = math.fmod(offset, probe_count) + probe_count
        
    # modulo
    w = (offset - 1) % probe_count

    # fix
    y = offset - 1
    z2 = math.fmod(math.fmod(y, probe_count) + probe_count, probe_count)
        
    return (offset, w, v, z2)

for i in range(-10, 10):
    res = f(i)
    print(f'"offset={res[0]:4}, mod={res[1]} ddgi={res[2]:4} fix={res[3]}')
```

And the output

```
"offset= -10, mod=1 ddgi= 2.0 fix=1.0
"offset=  -9, mod=2 ddgi= 3.0 fix=2.0
"offset=  -8, mod=3 ddgi= 4.0 fix=3.0
"offset=  -7, mod=4 ddgi= 5.0 fix=4.0
"offset=  -6, mod=5 ddgi= 6.0 fix=5.0
"offset=  -5, mod=0 ddgi= 1.0 fix=0.0
"offset=  -4, mod=1 ddgi= 2.0 fix=1.0
"offset=  -3, mod=2 ddgi= 3.0 fix=2.0
"offset=  -2, mod=3 ddgi= 4.0 fix=3.0
"offset=  -1, mod=4 ddgi= 5.0 fix=4.0
"offset=   0, mod=5 ddgi= 6.0 fix=5.0
"offset=   1, mod=0 ddgi= 0.0 fix=0.0
"offset=   2, mod=1 ddgi= 1.0 fix=1.0
"offset=   3, mod=2 ddgi= 2.0 fix=2.0
"offset=   4, mod=3 ddgi= 3.0 fix=3.0
"offset=   5, mod=4 ddgi= 4.0 fix=4.0
"offset=   6, mod=5 ddgi=-1.0 fix=5.0
"offset=   7, mod=0 ddgi= 0.0 fix=0.0
"offset=   8, mod=1 ddgi= 1.0 fix=1.0
"offset=   9, mod=2 ddgi= 2.0 fix=2.0


```

As you can see, the code that is currently in the SDK doesn't wrap correctly in some situations.
e.g.
```
"offset=  -6, mod=5 ddgi= 6.0 fix=5.0
"offset=   0, mod=5 ddgi= 6.0 fix=5.0
"offset=   6, mod=5 ddgi=-1.0 fix=5.0
```

L

**Comment by acmarrs-nvidia** [comment]
Hi @jirzynek - thanks very much for letting us know about this problem and taking the time to clearly explain the issue (with animations!). The latest release includes changes to fix the problem. This should be resolved, but if you have any issues still, feel free to reopen this issue and let us know what's going on.
