### ISSUE TITLE
Feature Request : make the SDK to be more friendly to be integrated with renderers which using SM6.6 bindless resources

### ISSUE THREAD

**Issue by zhaijialong** [NVIDIAGameWorks/RTXGI-DDGI#63]

**Comment by acmarrs-nvidia** [comment]
Hi @zhaijialong - thanks for the suggestion. The v1.3 update that I just posted includes support for bindless resources either through "traditional" resource arrays or [SM6.6's Dynamic Resources](https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_DynamicResources.html).

To take advantage of this, you'll need to [update how resource indices are passed to a DDGIVolume](https://github.com/NVIDIAGameWorks/RTXGI/blob/main/docs/DDGIVolume.md#resource-indices) and [let the shaders know the type of bindless you are using](https://github.com/NVIDIAGameWorks/RTXGI/blob/main/docs/DDGIVolume.md#preparing-shaders). Enjoy :-)
