### ISSUE TITLE
How to make the UE4 RTXGI plugin working in Linux?

### ISSUE THREAD

**Issue by hwwxj** [NVIDIAGameWorks/RTXGI-DDGI#64]
Since the UE4 RTXGI plugin requires DXR, which is not support in Linux. If we want to make it working in Linux, what do we need to do? which part of code is using DXR, can we change them to Vulkan Ray Tracing Extensions?  
Can anybody tell us in details? 
Truly appreciate.

**Comment by acmarrs-nvidia** [comment]
Hi @hwwxj - the UE4 RTXGI plugin executes graphics commands through Unreal's RHI. In UE4, only the D3D12 RHI supports ray tracing (via DXR). The Vulkan RHI does not support ray tracing which prevents the RTXGI plugin from ray tracing with Vulkan on Linux. Since UE4 is end-of-life, it is highly unlikely this limitation will change.

**Comment by hwwxj** [comment]
ok, so once in UE5, the Vulkan RHI support ray tracing, then we can use the RTXGI plugin in Linux.

**Comment by hwwxj** [comment]
ok, so once in UE5, the Vulkan RHI support ray tracing, then we can use the UE RTXGI plugin in Linux, right?  
 I can see some developers are discussing about this in UE's community.
https://forums.unrealengine.com/t/ray-tracing-support-using-the-vulkan-rhi-4-27-5-0/266937

> Hi @hwwxj - the UE4 RTXGI plugin executes graphics commands through Unreal's RHI. In UE4, only the D3D12 RHI supports ray tracing (via DXR). The Vulkan RHI does not support ray tracing which prevents the RTXGI plugin from ray tracing with Vulkan on Linux. Since UE4 is end-of-life, it is highly unlikely this limitation will change.

**Comment by acmarrs-nvidia** [comment]
Right, since it is unlikely UE4 will ever receive RT support in the Vulkan RHI, moving to UE5 will be necessary. Once UE5 adds RT support to it's Vulkan RHI, then the plugin will be able to use it.

**Comment by hwwxj** [comment]
> Right, since it is unlikely UE4 will ever receive RT support in the Vulkan RHI, moving to UE5 will be necessary. Once UE5 adds RT support to it's Vulkan RHI, then the plugin will be able to use it.

Get it. Thanks!

**Comment by oscarbg** [comment]
Hi @acmarrs-nvidia ,
seems upcoming 5.1 release supports that:
I see under https://portal.productboard.com/epicgames/1-unreal-engine-public-roadmap/c/845-lumen-improvements:
"Experimental: Hardware Ray Tracing (HWRT) in Vulkan - Surface cache lighting only, no support yet for Hit Lighting"
should be that enough for RTXGI support in UE5.1?
