### ISSUE TITLE
why ddgi cannot act normally in ue5 using vulkan?

### ISSUE THREAD

**Issue by Gnnnn** [NVIDIAGameWorks/RTXGI-DDGI#65]
Hi there, I wanna to know if the latest ddgi support vulkan?
I downloaded ue5.0.3 and opened the default option of using vulkan, but my ddgi sample just lost the indirect light.
Can anyone help me plz？

**Comment by acmarrs-nvidia** [comment]
Hi @Gnnnn - the RTXGI plugin does not currently include support for UE5's Vulkan RHI. If you are on Windows, you should switch to the D3D12 RHI.
