### ISSUE TITLE
NVIDIA Projects and License

### ISSUE THREAD

**Issue by KlingelingelingDerEiermann** [NVIDIAGameWorks/RTXGI-DDGI#66]
I don't know if you noticed, but AMD is now planning a comparable library for Ray Traced Global Illumination.
https://twitter.com/GPUOpen/status/1582434237583527936

Every graphics card manufacturer except NVIDIA releases their libraries under an open source license.

So why use the NVIDIA library when NVIDIA is the only company whose libraries are licensed under a proprietary license. And what is the reason? I know you don't know me, but I still want to make you think, because I think that many smaller engines are put off by such licenses.
Please release the libraries under an open license, you will benefit eventually.

**Comment by acmarrs-nvidia** [comment]
Hi @KlingelingelingDerEiermann - thanks for the feedback. I'll pass your message along to those who make decisions on these sort of things.

**Comment by KlingelingelingDerEiermann** [comment]
So you got no response from these people?
