### ISSUE TITLE
TestHarness: glTF 2.0 Spec conformance baseColorFactor

### ISSUE THREAD

**Issue by JerNeth** [NVIDIAGameWorks/RTXGI-DDGI#67]
While scrolling through the closest hit shaders (CHS.hlsl:46) I've noticed that the albedo is directly sampled and not multiplied with the baseColorFactor, and the baseColorTexture does not appear to be sampled as a sRGB texture as specified in the glTF-2.0 specs (3.9.2):

> For example, assume an 8-bit RGBA value of [64, 124, 231, 255] is sampled from baseColorTexture and assume that baseColorFactor is given as [0.2, 1.0, 0.7, 1.0]. Then, the final base color value would be (after decoding the transfer function and multiplying by the factor)
`[0.051 * 0.2, 0.202 * 1.0, 0.799 * 0.7, 1.0 * 1.0] = [0.0102, 0.202, 0.5593, 1.0]`

Was this a conscious decision, am I missing something or is this a bug?

**Comment by acmarrs-nvidia** [comment]
Hi @JerNeth - thanks for the feedback. This wasn't a purposeful decision, just a miss when conforming with the GLTF 2.0 spec. I've updated the CHS and AHS shader entry points of the Test Harness to properly multiply values sampled from texture with the `baseColorFactor` provided in the material. These updates will be in the next release.
