### ISSUE TITLE
Missing const for DDGIVolume::GetScrollOffsets()

### ISSUE THREAD

**Issue by Iyeyasu** [NVIDIAGameWorks/RTXGI-DDGI#69]
The `GetScrollOffsets()` in `DDGIVolume.h` function is missing `const`, even though it is just a plain getter. This makes it harder to use in const-correct user code. Not a huge deal due to `const_cast` but should still be fixed.

**Comment by acmarrs-nvidia** [comment]
Hi @Iyeyasu - thanks for pointing this out. I've included the fix in the v1.3.6 release.
