### ISSUE TITLE
probeBrightnessThreshold not working as intended? (ProbeBlendingCS.hlsl)

### ISSUE THREAD

**Issue by rj200** [NVIDIAGameWorks/RTXGI-DDGI#70]
The change to the result if delta is bigger than probeBrightnessThreshold here:

https://github.com/NVIDIAGameWorks/RTXGI/blob/d9fd1d871ef4b640472d484a41074c935edefc1c/rtxgi-sdk/shaders/ddgi/ProbeBlendingCS.hlsl#L531

is later overwritten here:

https://github.com/NVIDIAGameWorks/RTXGI/blob/d9fd1d871ef4b640472d484a41074c935edefc1c/rtxgi-sdk/shaders/ddgi/ProbeBlendingCS.hlsl#L549

**Comment by acmarrs-nvidia** [comment]
Hi @rj200 - thanks for pointing this out! You are correct. This is now fixed and will be included in the next release.

**Comment by acmarrs-nvidia** [comment]
The latest release with this fix is now live. You can find the changes in `ProbeBlendingCS.hlsl` around this line: https://github.com/NVIDIAGameWorks/RTXGI/blob/c233266e95931231961f35c842c78e7c4bdc50cf/rtxgi-sdk/shaders/ddgi/ProbeBlendingCS.hlsl#L529
