### ISSUE TITLE
UE5.1 support

### ISSUE THREAD

**Issue by ScottGelber** [NVIDIAGameWorks/RTXGI-DDGI#71]

**Comment by oscarbg** [comment]
Maybe given 5.2 preview coming shortly maybe better to focus on 5.2 already? Just saying.. no strong preference

**Comment by ScottGelber** [comment]
What a dick

**Comment by tiont** [comment]
Hi @oscarbg . Currently there are no plans to add support for any UE5 version beyond 5.0 in the RTXGI UE plugin. If you are looking for a performant and scalable indirect lighting solution for UE4.27 or UE5.0, RTXGI remains a great option and we will continue to support developers working with those versions.

**Comment by wickerman123** [comment]
Have there been any changes on the plans to support UE5? 

RTXGI is still a favourable solution over Lumen in some cases. For example, Lumen GI can not be used alongside Lightmaps.

RTXGI allows a nice combination of static lighting and dynamic GI from dynamic lighting - while not realistic, this is still something that is useful.

**Comment by tiont** [comment]
Hi @wickerman123 . Thank you for your comment. We appreciate the feedback on RTXGI and it's value for your use case. Unfortunately, we don't have any updates to share on the RTXGI UE5 plugin status at this time. We continue to work on improving and optimizing our lighting solutions in UE5. Please stay tuned for more info.
