### ISSUE TITLE
Help with Implementing in Unity

### ISSUE THREAD

**Issue by fabididabidi** [NVIDIAGameWorks/RTXGI-DDGI#72]
Hey, I've been searching for a performant realtime global illumination solution for over a week now and stumbled upon this project. 
So far, I have only found one implementation for Unreal Engine.
I'm not a graphics programmer, so I wanted to ask if you could give me a rough guide on how to get it up and running in Unity. 
Thanks in advance.

**Comment by LIVENDA** [comment]
GPT4

**Comment by acmarrs-nvidia** [comment]
Hi @fabididabidi - thanks for your interest in RTXGI. We don't support Unity at this time.
