### ISSUE TITLE
Test Harness fails to Initialise on Vulkan

### ISSUE THREAD

**Issue by Nolram12345** [NVIDIAGameWorks/RTXGI-DDGI#75]
System specifications:
OS Version : Windows 10 Version 6.2.9200
GPU : NVIDIA GeForce RTX 2060
CPU: AMD Ryzen 7 2700X
Built with Visual Studio 2022 against Vulkan SDK 1.3.261.1.

When starting the Vulkan-based Test Harness, the application does not initialise and outputs the following error message:
![image](https://github.com/NVIDIAGameWorks/RTXGI/assets/37701550/d11db74c-8b3a-4a82-aed6-6ad9429aec5c)

The log states the following:
```
Parsing command line...done.
Loading config file...done.
Creating a window...done.
Initializing input system...done.
Creating graphics device...done.
Initializing texture system...done.
Initializing the scene...done.
Initializing graphics...
Failed to create swap chain!
Failed to initialize graphics!
```

**Comment by acmarrs-nvidia** [comment]
Hi @Nolram12345 - thanks for pointing this out. I installed Vulkan SDK v1.3.261 and wasn't able to reproduce a swap chain create failure. I did find some validation layer errors and pushed a fix for those, but they shouldn't affect the problem you're hitting.

In `Vulkan.cpp::CreateSwapChain(...)` there are several spots where failures can occur. Can you drop a breakpoint on [line 70 of Vulkan.cpp](https://github.com/NVIDIAGameWorks/RTXGI/blob/0df12abbd3558456a8da5b0349a732a9f02e98ff/samples/test-harness/src/Vulkan.cpp#L70) to see what's going on? If you can provide the `VkResult` passed to the `Check(...)` function as well as the callstack, that would be much appreciated!

**Comment by Nolram12345** [comment]
I have re-cloned the project and re-built everything according to the instructions, this time also using VS2019 instead of VS2022. The Test Harness now runs correctly; this *may* be worth further investigation, but I got all to work now on my end. Thanks for the assistance!

**Comment by dandingol03** [comment]
sad for VS2022

**Comment by dandingol03** [comment]
Hi, i solve this crash by modifying the swapchain size in `config`. There are some assertions when compare the swpachain's size.
