### ISSUE TITLE
TestHarness-VK is failing at Creating swap chain on Windows 11

### ISSUE THREAD

**Issue by Raki** [NVIDIAGameWorks/RTXGI-DDGI#77]
I tried to run TestHarness-VK on Windows.

Application is failing to create Swapchain.

The reason is extent of the **VkSurfaceCapabilitiesKHR** . It is not matching with the extent with which the glfw window is created, which is 1920x1080 in this case.

![image](https://github.com/NVIDIAGameWorks/RTXGI/assets/824691/d96fc8a3-0ebd-42e3-9cd8-f5f011236bff)

If I use default app dimensions(1280x720), there is no issue with the swapchain creation and  the app runs fine. At this instance if I choose 1920x1080 resolution from the imgui interface there is no issue.
![image](https://github.com/NVIDIAGameWorks/RTXGI/assets/824691/d3a9c09a-ddcf-4081-bd66-e1ade66b8694)

**Comment by acmarrs-nvidia** [comment]
Hi @Raki - is the resolution of your screen <= 1920x1080? The 1061 value you're seeing for the Y dimension seems like 1080 - the window header's height. `VkSurfaceCapabilitiesKHR` seems to think the device and surface combo you have doesn't support the full 1080p resolution.

You have a few options. The first to try is change the resolution dimensions to a lower value in the scene .ini file you are loading (e.g. see [cornell.ini](https://github.com/NVIDIAGameWorks/RTXGI/blob/0df12abbd3558456a8da5b0349a732a9f02e98ff/samples/test-harness/config/cornell.ini#L5)). All scenes default to 1920x1080, but you can change them to anything you want. Another option is to remove the checks in [Vulkan.cpp](https://github.com/NVIDIAGameWorks/RTXGI/blob/0df12abbd3558456a8da5b0349a732a9f02e98ff/samples/test-harness/src/Vulkan.cpp#L496) that ensure the swapchain dimensions match the resolution dimensions specified by the .ini file. This isn't recommended though.

**Comment by Raki** [comment]
Hi @acmarrs-nvidia I can confirm that my screen resolution is 1920x1080.  I am able to run the demo with lower resolution 1280x720. If I change the resolution back to 1920x1080 from Settings windows (Resoution Preset), I can see the output with 1920x1061

![image](https://github.com/NVIDIAGameWorks/RTXGI/assets/824691/1be95022-01cb-4f32-b7cf-f5dc0152dac9)

**Comment by acmarrs-nvidia** [comment]
Hmm, well that's weird. The FHD preset should set the application to 1920x1080 - so it reporting 1061 for the height is...wrong. For some reason it seems `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` is returning 1061 as the maximum pixel height supported by your device. 

Do you have the latest drivers for your graphics device installed? Are you using a fairly recent version of the Vulkan SDK?

**Comment by Raki** [comment]
My Graphics driver is up to date.

**Comment by Raki** [comment]
My Graphics driver is up to date.
![image](https://github.com/NVIDIAGameWorks/RTXGI/assets/824691/c4a8c89e-5a73-4ba4-9b79-0eed182f35d9)

I'm using LunarG Vulkan SDK :  **1.3.268.0**

**Comment by acmarrs-nvidia** [comment]
I tried to reproduce this issue on my side (using 1440p resolution instead), but am not able to. Since this issue is ultimately not related to RTXGI directly, but I'd recommend simply commenting out the checks on line 496 and 497 of Vulkan.cpp. This will allow the swapchain to be created using the allowed (slightly smaller) dimensions, even though they don't match the requested dimensions.
