### ISSUE TITLE
farthestFrontfaceDistance usage in ProbeRelocationCS.hlsl

### ISSUE THREAD

**Issue by TLeonardUK** [NVIDIAGameWorks/RTXGI-DDGI#78]
I notice on line 211 of ProbeRelocationCS.hlsl, you scale farthestFrontfaceDistance but do nothing further with it, the line below also sets the fullOffset to the offset plus the direction unit vector.

```hlsl
        if (dot(closestFrontfaceDirection, farthestFrontfaceDirection) <= 0.f)
        {
            // Ensures the probe never moves through the farthest frontface
            farthestFrontfaceDistance *= min(farthestFrontfaceDistance, 1.f);
            fullOffset = offset + farthestFrontfaceDirection;
        }
```

Should this not be taking the distance into account when calculating the fullOffset (and presumably the min frontface distance)?

**Comment by jukim-nv** [comment]
@TLeonardUK I believe you are correct.  I probably made a mistake when writing this and meant to scale `farthestFrontfaceDirection` by the `min()` result instead.

**Comment by acmarrs-nvidia** [comment]
I've pushed @jukim-nv's fix to main. It is [available here](https://github.com/NVIDIAGameWorks/RTXGI/commit/a6c4d9917ac6223be9ee97f304b7d92c20dda970).
