### ISSUE TITLE
error at update_dependecies.bat

### ISSUE THREAD

**Issue by stylixpro** [NVIDIAGameWorks/RTXGI-DDGI#79]
Error occurs when update_dependencies.bat
----------
Processing project file 'packman\dependencies.xml'
Package 'dxc' at version '1.7.2207-windows-x86_64' is missing from local storage.
packman(ERROR): Unable to download file from 'https://d4i3qtqj3r0z5.cloudfront.net/dxc%401.7.2207-windows-x86_64' (server returned 403)

**Comment by acmarrs-nvidia** [comment]
Hi @stylixpro - sorry about this. The issue has been resolved with the latest commit. External binary dependencies are now handled with CMake.
