### ISSUE TITLE
Question: no longer using NoCheb fallback term?

### ISSUE THREAD

**Issue by ALEXMORF** [NVIDIAGameWorks/RTXGI-DDGI#8]
Hi. I remember from Mcguire's original GDC talk, during irradiance evaluation, it falls back to classic irradiance probe evaluation if most lighting contribution is crushed by chebyshev's inequality. That doesn't seem to have been implemented in this SDK. Did it not perform well? or was it replaced by something? Thanks.

**Comment by acmarrs-nvidia** [comment]
When chebyshev's inequality is used during irradiance evaluation, the shaded point is occluded in the direction towards the probe being sampled. As a result, the contribution of the probe needs to be decreased substantially for the algorithm to prevent light leaking. Falling back to sampling irradiance from the probe (aka "classic" irradiance probe evaluation) would leak light. 

Let me know if I've misunderstood your question though.

**Comment by ALEXMORF** [comment]
Hi Adam, thanks for the reply. That makes perfect sense to me. But then I'm really confused by this slide from the GDC talk on DDGI:

![image](https://user-images.githubusercontent.com/16845654/79245778-66b53080-7e2d-11ea-8ca5-45494c6f1d7b.png)

What is the IrradianceNoCheb term here then? My understanding was this is the classic irradiance fallback, but clearly this would lead to light leaking. So I'm not sure what this term really is.

**Comment by acmarrs-nvidia** [comment]
Ah, okay, now I understand where your question is coming from. The early academic version of the algorithm presented in that talk included a special fallback for when a probe had no visibility. This was removed for clarity and performance reasons (as you suspected) in the SDK.

**Comment by ALEXMORF** [comment]
Gotcha, thanks!
