### ISSUE TITLE
Quick query for Unreal Engine 5.x

### ISSUE THREAD

**Issue by alexpanter** [NVIDIAGameWorks/RTXGI-DDGI#80]
Hi, just a quick question - how supported/unsupported is Unreal Engine 5(.x) for this plugin? UE 4 is mentioned in several places, so I'm just curious to hear. Didn't try it out yet.

Thanks!

**Comment by acmarrs-nvidia** [comment]
Hi @alexpanter, UE5.x is not officially supported. An RTXGI plugin exists for 5.0, but 5.1 and later are not supported. You can access the 5.0 plugin [here](https://developer.nvidia.com/rtx/ray-tracing/rtxgi/get-started#ue4-requirements).
