### ISSUE TITLE
Warnings in the shaders.

### ISSUE THREAD

**Issue by kingofthebongo2008** [NVIDIAGameWorks/RTXGI-DDGI#9]
Hey, I have got a lot of these. I wonder is this my error to look at them?

Since i have took the shaders and integrated in the msbuild system to compile them offline. 
All the best.

1>..\src\shaders/../../samples/test-harness/shaders/Indirect.hlsl(59,42): warning GBFFABD58: implicit truncation of vector type
1>        float3 diffuse = RTGBufferD.Load(int3(input.position.xy, 0)).rgb;
1>                                         ^
1>..\src\shaders/../../samples/test-harness/shaders/Indirect.hlsl(62,56): warning GBFFABD58: implicit truncation of vector type
1>        ambientOcclusion = UseRTAO ? RTAOFiltered.Load(int3(input.position.xy, 0)) : 1.f;

**Comment by acmarrs-nvidia** [comment]
@kingofthebongo2008, thanks for pointing this out. The latest commit has changes to address this. The shader compilation flow of the Test Harness sample application now has the option to treat warnings as errors. I've also updated the offending shaders to fix warnings. The primary issue was calling Load() on RWTexture2D resources and supplying int3 coordinates. Mipmap level can't be specified in shaders for this resource type, so an int2 is the proper argument type.
